ultra64: src/n64/MMU.cpp File Reference
MMU.cpp File Reference
#include "MMU.hpp"
#include "rcp/RSP.hpp"
#include <iostream>
#include <sstream>
#include <cstring>
Functions
void dp_register_read (MMU *mmu, memory_section s, uint64_t value)
void dp_register_write (MMU *mmu, memory_section s, uint64_t value)
void pi_register_write (MMU *mmu, memory_section s, uint64_t value)
void pif_ram_write (MMU *mmu, memory_section s, uint64_t value)
void si_register_read (MMU *mmu, memory_section s, uint64_t value)
void si_register_write (MMU *mmu, memory_section s, uint64_t value)
void sp_dmem_write (MMU *mmu, memory_section s, uint64_t value)
void sp_register_read (MMU *mmu, memory_section s, uint64_t value)
void sp_register_write (MMU *mmu, memory_section s, uint64_t value)
Function Documentation
dp_register_read()
void dp_register_read (MMU * mmu, memory_section s, uint64_t value)
Definition at line 98 of file MMU.cpp.
 {
     std::cout << "    dp_register_read(): Read " << std::hex << value << " from " << s.addr << std::endl;
 }
References ultra64::memory_section::addr.
Referenced by ultra64::MMU::MMU().
dp_register_write()
void dp_register_write (MMU * mmu, memory_section s, uint64_t value)
Definition at line 93 of file MMU.cpp.
 {
     std::cout << "    dp_register_write(): Wrote " << std::hex << value << " to " << s.addr << std::endl;
 }
References ultra64::memory_section::addr.
Referenced by ultra64::MMU::MMU().
pi_register_write()
void pi_register_write (MMU * mmu, memory_section s, uint64_t value)
Definition at line 47 of file MMU.cpp.
 {
     std::cout << "    pi_register_write(): Wrote " << std::hex << value << " to " << s.addr << std::endl;
 }
References ultra64::memory_section::addr.
Referenced by ultra64::MMU::MMU().
pif_ram_write()
void pif_ram_write (MMU * mmu, memory_section s, uint64_t value)
Definition at line 88 of file MMU.cpp.
 {
     std::cout << "    pif_ram_write(): Wrote " << std::hex << value << " to " << s.addr << std::endl;
 }
References ultra64::memory_section::addr.
Referenced by ultra64::MMU::MMU().
si_register_read()
void si_register_read (MMU * mmu, memory_section s, uint64_t value)
Definition at line 70 of file MMU.cpp.
 {
     switch(s.addr)
     {
         case SI_STATUS_REG:
             std::cout << "  Reading from SI_STATUS_REG:" << std::endl;
             if(value & 0x01) std::cout << "    - DMA busy" << std::endl;
             if(value & 0x02) std::cout << "    - IO read busy" << std::endl;
             if(value & 0x04) std::cout << "    - Reserved" << std::endl;
             if(value & 0x08) std::cout << "    - DMA error" << std::endl;
             if(value & 0x0800) std::cout << "    - Interrupt" << std::endl;
             break;
         default:
             std::cout << "    si_register_read(): Read " << std::hex << value << " from " << s.addr << std::endl;
             break;
     }
 }
References ultra64::memory_section::addr, and SI_STATUS_REG.
Referenced by ultra64::MMU::MMU().
si_register_write()
void si_register_write (MMU * mmu, memory_section s, uint64_t value)
Definition at line 52 of file MMU.cpp.
 {
     switch(s.addr)
     {
         case SI_STATUS_REG:
             std::cout << "  Writing to SI_STATUS_REG:" << std::endl;
             if(value & 0x01) std::cout << "    - DMA busy" << std::endl;
             if(value & 0x02) std::cout << "    - IO read busy" << std::endl;
             if(value & 0x04) std::cout << "    - Reserved" << std::endl;
             if(value & 0x08) std::cout << "    - DMA error" << std::endl;
             if(value & 0x0800) std::cout << "    - Interrupt" << std::endl;
             break;
         default:
             std::cout << "    si_register_write(): Wrote " << std::hex << value << " to " << s.addr << std::endl;
             break;
     }
 }
References ultra64::memory_section::addr, and SI_STATUS_REG.
sp_dmem_write()
void sp_dmem_write (MMU * mmu, memory_section s, uint64_t value)
Definition at line 103 of file MMU.cpp.
 {
     std::cout << "    sp_dmem_write(): Wrote " << std::hex << value << " to " << s.addr << std::endl;
 }
References ultra64::memory_section::addr.
Referenced by ultra64::MMU::MMU().
sp_register_read()
void sp_register_read (MMU * mmu, memory_section s, uint64_t value)
Definition at line 26 of file MMU.cpp.
 {
     switch(s.addr)
     {
         case SP_STATUS_REG:
             std::cout << "  Reading from SP_STATUS_REG:" << std::endl;
             if(value & 0x01) std::cout << "    - Halt" << std::endl;
             if(value & 0x02) std::cout << "    - Broke" << std::endl;
             if(value & 0x04) std::cout << "    - DMA busy" << std::endl;
             if(value & 0x08) std::cout << "    - DMA full" << std::endl;
             break;
         case SP_DMA_BUSY_REG:
             std::cout << "  Reading from SP_DMA_BUSY_REG:" << std::endl;
             if(value & 0x01) std::cout << "    - Busy" << std::endl;
             break;
         default:
             std::cout << "    sp_register_read(): Read " << std::hex << value << " from " << s.addr << std::endl;
             break;
     }
 }
References ultra64::memory_section::addr, SP_DMA_BUSY_REG, and SP_STATUS_REG.
Referenced by ultra64::MMU::MMU().
sp_register_write()
void sp_register_write (MMU * mmu, memory_section s, uint64_t value)
Definition at line 9 of file MMU.cpp.
 {
     switch(s.addr)
     {
         case SP_STATUS_REG:
             std::cout << "  Writing to SP_STATUS_REG:" << std::endl;
             if(value & 0x01) std::cout << "    - Clear halt" << std::endl;
             if(value & 0x02) std::cout << "    - Set halt" << std::endl;
             if(value & 0x04) std::cout << "    - Clear broke" << std::endl;
             if(value & 0x08) std::cout << "    - Clear interrupt" << std::endl;
             break;
         default:
             std::cout << "    sp_register_write(): Wrote " << std::hex << value << " to " << s.addr << std::endl;
             break;
     }
 }
References ultra64::memory_section::addr, and SP_STATUS_REG.
Referenced by ultra64::MMU::MMU().