ultra64: ultra64::vr4300 Class Reference
ultra64::vr4300 Class Reference
#include <vr4300.hpp>
Public Member Functions
vr4300 (MMU &mmu)
uint32_t get_PC ()
IMPL_OP (_or)
IMPL_OP (addi)
IMPL_OP (addiu)
IMPL_OP (andi)
IMPL_OP (beq)
IMPL_OP (beql)
IMPL_OP (bgezal)
IMPL_OP (bltz)
IMPL_OP (bne)
IMPL_OP (bnel)
IMPL_OP (cp0)
IMPL_OP (daddi)
IMPL_OP (dsll32)
IMPL_OP (jr)
IMPL_OP (lui)
IMPL_OP (lw)
IMPL_OP (mflo)
IMPL_OP (mtc0)
IMPL_OP (multu)
IMPL_OP (not_implemented)
IMPL_OP (ori)
IMPL_OP (regimm)
IMPL_OP (sll)
IMPL_OP (sltu)
IMPL_OP (special)
IMPL_OP (srl)
IMPL_OP (sw)
void step ()
Private Attributes
uint64_t CP0 [32] = { 0 }
uint32_t current_instruction
uint64_t GPR [32] = { 0 }
uint32_t HI
uint32_t LO
MMU * mmu
void(* opcode [0x40])(vr4300 *)
void(* opcode_cp0 [0x40])(vr4300 *)
void(* opcode_regimm [0x40])(vr4300 *)
void(* opcode_special [0x40])(vr4300 *)
uint32_t PC
Detailed Description
Definition at line 11 of file vr4300.hpp.
Constructor & Destructor Documentation
vr4300()
vr4300::vr4300 (MMU & mmu)
Definition at line 10 of file vr4300.cpp.
 {
     this->mmu = &mmu;
     for(int i = 0; i < 0x40; i++)
     {
         this->opcode[i] = this->opcode_cp0[i] = this->opcode_special[i] = this->opcode_regimm[i] = vr4300::not_implemented;
     }
     this->opcode[_SPECIAL] = vr4300::special;
     this->opcode[_REGIMM] = vr4300::regimm;
     this->opcode[BEQ] = vr4300::beq;
     this->opcode[BNE] = vr4300::bne;
     this->opcode[ADDI] = vr4300::addi;
     this->opcode[ADDIU] = vr4300::addiu;
     this->opcode[ANDI] = vr4300::andi;
     this->opcode[ORI] = vr4300::ori;
     this->opcode[LUI] = vr4300::lui;
     this->opcode[_CP0] = vr4300::cp0;
     this->opcode[BEQL] = vr4300::beql;
     this->opcode[BNEL] = vr4300::bnel;
     this->opcode[DADDI] = vr4300::daddi;
     this->opcode[LW] = vr4300::lw;
     this->opcode[SW] = vr4300::sw;
     this->opcode_special[SLL] = vr4300::sll;
     this->opcode_special[SRL] = vr4300::srl;
     this->opcode_special[JR] = vr4300::jr;
     this->opcode_special[MFLO] = vr4300::mflo;
     this->opcode_special[MULTU] = vr4300::multu;
     this->opcode_special[OR] = vr4300::_or;
     this->opcode_special[SLTU] = vr4300::sltu;
     this->opcode_special[DSLL32] = vr4300::dsll32;
     this->opcode_regimm[BLTZ] = vr4300::bltz;
     this->opcode_regimm[BGEZAL] = vr4300::bgezal;
     this->opcode_cp0[MTC0] = vr4300::mtc0;
     this->PC = 0x1FC00000;
 }
References ultra64::_CP0, ultra64::_REGIMM, ultra64::_SPECIAL, ultra64::ADDI, ultra64::ADDIU, ultra64::ANDI, ultra64::BEQ, ultra64::BEQL, ultra64::BGEZAL, ultra64::BLTZ, ultra64::BNE, ultra64::BNEL, ultra64::DADDI, ultra64::DSLL32, ultra64::JR, ultra64::LUI, ultra64::LW, ultra64::MFLO, mmu, ultra64::MTC0, ultra64::MULTU, opcode, opcode_cp0, opcode_regimm, opcode_special, ultra64::OR, ultra64::ORI, PC, ultra64::SLL, ultra64::SLTU, ultra64::SRL, and ultra64::SW.
Member Function Documentation
get_PC()
uint32_t vr4300::get_PC ()
Definition at line 52 of file vr4300.cpp.
 {
     return this->PC;
 }
References PC.
IMPL_OP() [1/27]
ultra64::vr4300::IMPL_OP (_or)
IMPL_OP() [2/27]
ultra64::vr4300::IMPL_OP (addi)
IMPL_OP() [3/27]
ultra64::vr4300::IMPL_OP (addiu)
IMPL_OP() [4/27]
ultra64::vr4300::IMPL_OP (andi)
IMPL_OP() [5/27]
ultra64::vr4300::IMPL_OP (beq)
IMPL_OP() [6/27]
ultra64::vr4300::IMPL_OP (beql)
IMPL_OP() [7/27]
ultra64::vr4300::IMPL_OP (bgezal)
IMPL_OP() [8/27]
ultra64::vr4300::IMPL_OP (bltz)
IMPL_OP() [9/27]
ultra64::vr4300::IMPL_OP (bne)
IMPL_OP() [10/27]
ultra64::vr4300::IMPL_OP (bnel)
IMPL_OP() [11/27]
ultra64::vr4300::IMPL_OP (cp0)
IMPL_OP() [12/27]
ultra64::vr4300::IMPL_OP (daddi)
IMPL_OP() [13/27]
ultra64::vr4300::IMPL_OP (dsll32)
IMPL_OP() [14/27]
ultra64::vr4300::IMPL_OP (jr)
IMPL_OP() [15/27]
ultra64::vr4300::IMPL_OP (lui)
IMPL_OP() [16/27]
ultra64::vr4300::IMPL_OP (lw)
IMPL_OP() [17/27]
ultra64::vr4300::IMPL_OP (mflo)
IMPL_OP() [18/27]
ultra64::vr4300::IMPL_OP (mtc0)
IMPL_OP() [19/27]
ultra64::vr4300::IMPL_OP (multu)
IMPL_OP() [20/27]
ultra64::vr4300::IMPL_OP (not_implemented)
IMPL_OP() [21/27]
ultra64::vr4300::IMPL_OP (ori)
IMPL_OP() [22/27]
ultra64::vr4300::IMPL_OP (regimm)
IMPL_OP() [23/27]
ultra64::vr4300::IMPL_OP (sll)
IMPL_OP() [24/27]
ultra64::vr4300::IMPL_OP (sltu)
IMPL_OP() [25/27]
ultra64::vr4300::IMPL_OP (special)
IMPL_OP() [26/27]
ultra64::vr4300::IMPL_OP (srl)
IMPL_OP() [27/27]
ultra64::vr4300::IMPL_OP (sw)
step()
void vr4300::step ()
Definition at line 57 of file vr4300.cpp.
 {
     this->current_instruction = mmu->read_word(this->PC);
     opcode_i_type icode(this->current_instruction);
     instruction i(this->current_instruction);
     std::cout << std::hex << this->PC << ": " << i.to_string() << std::endl;
     this->opcode[icode.op](this);
     this->CP0[9] += 2;
 }
References CP0, current_instruction, mmu, ultra64::opcode_i_type::op, opcode, PC, ultra64::MMU::read_word(), and ultra64::instruction::to_string().
Referenced by start().
Member Data Documentation
CP0
uint64_t ultra64::vr4300::CP0[32] = { 0 } private
Definition at line 50 of file vr4300.hpp.
Referenced by step().
current_instruction
uint32_t ultra64::vr4300::current_instruction private
Definition at line 55 of file vr4300.hpp.
Referenced by step().
GPR
uint64_t ultra64::vr4300::GPR[32] = { 0 } private
Definition at line 49 of file vr4300.hpp.
HI
uint32_t ultra64::vr4300::HI private
Definition at line 48 of file vr4300.hpp.
LO
uint32_t ultra64::vr4300::LO private
Definition at line 48 of file vr4300.hpp.
mmu
MMU* ultra64::vr4300::mmu private
Definition at line 56 of file vr4300.hpp.
Referenced by vr4300(), and step().
opcode
void(* ultra64::vr4300::opcode[0x40])(vr4300 *) private
Definition at line 51 of file vr4300.hpp.
Referenced by vr4300(), and step().
opcode_cp0
void(* ultra64::vr4300::opcode_cp0[0x40])(vr4300 *) private
Definition at line 52 of file vr4300.hpp.
Referenced by vr4300().
opcode_regimm
void(* ultra64::vr4300::opcode_regimm[0x40])(vr4300 *) private
Definition at line 54 of file vr4300.hpp.
Referenced by vr4300().
opcode_special
void(* ultra64::vr4300::opcode_special[0x40])(vr4300 *) private
Definition at line 53 of file vr4300.hpp.
Referenced by vr4300().
PC
uint32_t ultra64::vr4300::PC private
Definition at line 48 of file vr4300.hpp.
Referenced by vr4300(), get_PC(), and step().
The documentation for this class was generated from the following files:
src/vr4300/vr4300.hpp
src/vr4300/vr4300.cpp