ultra64: ultra64::instruction Class Reference
ultra64::instruction Class Reference
#include <instruction.hpp>
Public Member Functions
instruction (uint32_t)
std::string cp0_to_string ()
std::string cp1_to_string ()
std::string regimm_to_string ()
std::string special_to_string ()
std::string to_string ()
Private Attributes
uint32_t i
Detailed Description
Definition at line 7 of file instruction.hpp.
Constructor & Destructor Documentation
instruction()
instruction::instruction (uint32_t i)
Definition at line 11 of file instruction.cpp.
 {
     this->i =  i;
 }
References i.
Member Function Documentation
cp0_to_string()
std::string instruction::cp0_to_string ()
Definition at line 97 of file instruction.cpp.
 {
     std::stringstream ss;
     opcode_co_type opcode(this->i);
     switch(opcode.sub)
     {
         case MFC0:
             ss << "MFC0 " << std::dec << static_cast<unsigned>(opcode.rt) << ", " << static_cast<unsigned>(opcode.rd);
             break;
         case MTC0:
             ss << "MTC0 " << std::dec << static_cast<unsigned>(opcode.rt) << ", " << static_cast<unsigned>(opcode.rd);
             break;
         default:
             ss << "Unknown CP0 sub-opcode 0x" << std::hex << upper << static_cast<unsigned>(opcode.sub);
             break;
     }
     return ss.str();
 }
References i, ultra64::MFC0, ultra64::MTC0, ultra64::opcode_co_type::rd, ultra64::opcode_co_type::rt, and ultra64::opcode_co_type::sub.
Referenced by to_string().
cp1_to_string()
std::string instruction::cp1_to_string ()
Definition at line 118 of file instruction.cpp.
 {
     std::stringstream ss;
     opcode_co_type opcode(this->i);
     switch(opcode.sub)
     {
         case MFC1:
             ss << "MFC1 " << std::dec << static_cast<unsigned>(opcode.rt) << ", " << static_cast<unsigned>(opcode.rd);
             break;
         default:
             ss << "Unknown CP1 sub-opcode 0x" << std::hex << upper << static_cast<unsigned>(opcode.sub);
             break;
     }
     return ss.str();
 }
References i, ultra64::MFC1, ultra64::opcode_co_type::rd, ultra64::opcode_co_type::rt, and ultra64::opcode_co_type::sub.
Referenced by to_string().
regimm_to_string()
std::string instruction::regimm_to_string ()
Definition at line 199 of file instruction.cpp.
 {
     std::stringstream ss;
     opcode_regimm_type opcode(this->i);
     switch(opcode.rt)
     {
         case BLTZ:
             ss << "BLTZ " << std::dec << static_cast<unsigned>(opcode.rs) << ", " << std::hex << upper << static_cast<unsigned>(opcode.offset);
             break;
         case BGEZAL:
             ss << "BGEZAL " << std::dec << static_cast<unsigned>(opcode.rs) << ", " << std::hex << upper << static_cast<unsigned>(opcode.offset);
             break;
         default:
             ss << "Unknown REGIMM sub-opcode 0x" << std::hex << upper << static_cast<unsigned>(opcode.rt);
             break;
     }
     return ss.str();
 }
References ultra64::BGEZAL, ultra64::BLTZ, i, ultra64::opcode_regimm_type::offset, ultra64::opcode_regimm_type::rs, and ultra64::opcode_regimm_type::rt.
Referenced by to_string().
special_to_string()
std::string instruction::special_to_string ()
Definition at line 136 of file instruction.cpp.
 {
     std::stringstream ss;
     opcode_special_type opcode(this->i);
     switch(opcode.function)
     {
         case SLL:
             ss << "SLL " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rt) << ", " << static_cast<unsigned>(opcode.sa);
             break;
         case SRL:
             ss << "SRL " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rt) << ", " << static_cast<unsigned>(opcode.sa);
             break;
         case SLLV:
             ss << "SLLV " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rt) << ", " << static_cast<unsigned>(opcode.sa);
             break;
         case SRLV:
             ss << "SRLV " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rt) << ", " << static_cast<unsigned>(opcode.sa);
             break;
         case JR:
             ss << "JR " << std::dec << static_cast<unsigned>(opcode.rs);
             break;
         case MFHI:
             ss << "MFHI " << std::dec << static_cast<unsigned>(opcode.rd);
             break;
         case MFLO:
             ss << "MFLO " << std::dec << static_cast<unsigned>(opcode.rd);
             break;
         case MTLO:
             ss << "MTLO " << std::dec << static_cast<unsigned>(opcode.rd);
             break;
         case MULTU:
             ss << "MULTU " << std::dec << static_cast<unsigned>(opcode.rs) << ", " << static_cast<unsigned>(opcode.rt);
             break;
         case ADDU:
             ss << "ADDU " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rs) << ", " << static_cast<unsigned>(opcode.rt);
             break;
         case SUBU:
             ss << "SUBU " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rs) << ", " << static_cast<unsigned>(opcode.rt);
             break;
         case AND:
             ss << "AND " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rs) << ", " << static_cast<unsigned>(opcode.rt);
             break;
         case OR:
             ss << "OR " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rs) << ", " << static_cast<unsigned>(opcode.rt);
             break;
         case XOR:
             ss << "XOR " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rs) << ", " << static_cast<unsigned>(opcode.rt);
             break;
         case SLTU:
             ss << "SLTU " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rs) << ", " << static_cast<unsigned>(opcode.rt);
             break;
         case DSLL32:
             ss << "DSLL32 " << std::dec << static_cast<unsigned>(opcode.rd) << ", " << static_cast<unsigned>(opcode.rt) << ", " << static_cast<unsigned>(opcode.sa);
             break;
         default:
             ss << "Unknown SPECIAL sub-opcode 0x" << std::hex << upper << static_cast<unsigned>(opcode.function);
             break;
     }
     return ss.str();
 }
References ultra64::ADDU, ultra64::AND, ultra64::DSLL32, ultra64::opcode_special_type::function, i, ultra64::JR, ultra64::MFHI, ultra64::MFLO, ultra64::MTLO, ultra64::MULTU, ultra64::OR, ultra64::opcode_special_type::rd, ultra64::opcode_special_type::rs, ultra64::opcode_special_type::rt, ultra64::opcode_special_type::sa, ultra64::SLL, ultra64::SLLV, ultra64::SLTU, ultra64::SRL, ultra64::SRLV, ultra64::SUBU, and ultra64::XOR.
Referenced by to_string().
to_string()
std::string instruction::to_string ()
Definition at line 16 of file instruction.cpp.
 {
     std::stringstream ss;
     uint32_t target;
     opcode_i_type opcode(this->i);
     switch(opcode.op)
     {
         case _SPECIAL:
             return this->special_to_string();
             break;
         case _REGIMM:
             return this->regimm_to_string();
             break;
         case JAL:
             target = this->i & 0x3FFFFFF;
             ss << "JAL 0x" << std::hex << upper << target;
             break;
         case BEQ:
             ss << "BEQ " << std::dec << static_cast<unsigned>(opcode.rs) << ", "
                << static_cast<unsigned>(opcode.rt) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case BNE:
             ss << "BNE " << std::dec << static_cast<unsigned>(opcode.rs) << ", "
                << static_cast<unsigned>(opcode.rt) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case ADDI:
             ss << "ADDI " << std::dec << static_cast<unsigned>(opcode.rt) << ", "
                << static_cast<unsigned>(opcode.rs) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case ADDIU:
             ss << "ADDIU " << std::dec << static_cast<unsigned>(opcode.rt) << ", "
                << static_cast<unsigned>(opcode.rs) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case ANDI:
             ss << "ANDI " << std::dec << static_cast<unsigned>(opcode.rt) << ", "
                << static_cast<unsigned>(opcode.rs) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case ORI:
             ss << "ORI " << std::dec << static_cast<unsigned>(opcode.rt) << ", "
                << static_cast<unsigned>(opcode.rs) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case LUI:
             ss << "LUI " << std::dec << static_cast<unsigned>(opcode.rt) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case _CP0:
             return this->cp0_to_string();
             break;
         case _CP1:
             return this->cp1_to_string();
             break;
         case BEQL:
             ss << "BEQL " << std::dec << static_cast<unsigned>(opcode.rs) << ", "
                << static_cast<unsigned>(opcode.rt) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case BNEL:
             ss << "BNEL " << std::dec << static_cast<unsigned>(opcode.rs) << ", "
                << static_cast<unsigned>(opcode.rt) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case DADDI:
             ss << "DADDI " << std::dec << static_cast<unsigned>(opcode.rs) << ", "
                << static_cast<unsigned>(opcode.rt) << ", 0x" << std::hex << upper << opcode.immediate;
             break;
         case LW:
             ss << "LW " << std::dec << static_cast<unsigned>(opcode.rt) << ", 0x" << std::hex << upper << opcode.immediate << "(" << std::dec << static_cast<unsigned>(opcode.rs) << ")";
             break;
         case SW:
             ss << "SW " << std::dec << static_cast<unsigned>(opcode.rt) << ", 0x" << std::hex << upper << opcode.immediate << "(" << std::dec << static_cast<unsigned>(opcode.rs) << ")";
             break;
         case SD:
             ss << "SD " << std::dec << static_cast<unsigned>(opcode.rt) << ", 0x" << std::hex << upper << opcode.immediate << "(" << std::dec << static_cast<unsigned>(opcode.rs) << ")";
             break;
         default:
             ss << "Unknown opcode 0x" << std::hex << upper << static_cast<unsigned>(opcode.op);
             break;
     }
     return ss.str();
 }
References ultra64::_CP0, ultra64::_CP1, ultra64::_REGIMM, ultra64::_SPECIAL, ultra64::ADDI, ultra64::ADDIU, ultra64::ANDI, ultra64::BEQ, ultra64::BEQL, ultra64::BNE, ultra64::BNEL, cp0_to_string(), cp1_to_string(), ultra64::DADDI, i, ultra64::opcode_i_type::immediate, ultra64::JAL, ultra64::LUI, ultra64::LW, ultra64::opcode_i_type::op, ultra64::ORI, regimm_to_string(), ultra64::opcode_i_type::rs, ultra64::opcode_i_type::rt, ultra64::SD, special_to_string(), ultra64::SW, and upper.
Referenced by ultra64::vr4300::step(), and DebuggerWindow::view().
Member Data Documentation
i
uint32_t ultra64::instruction::i private
Definition at line 17 of file instruction.hpp.
Referenced by instruction(), cp0_to_string(), cp1_to_string(), regimm_to_string(), special_to_string(), and to_string().
The documentation for this class was generated from the following files:
src/n64/instruction.hpp
src/n64/instruction.cpp