ultra64: wxUltra64 Class Reference
wxUltra64 Class Reference
#include <ultra64.hpp>
Public Member Functions
Json::Value load_config ()
virtual bool OnInit ()
void save_config ()
Public Attributes
Json::Value config
std::string config_path = ".config/ultra64"
DebuggerWindow * debugger = nullptr
MainWindow * frame = nullptr
ultra64::N64 * n64 = nullptr
RegistersWindow * registers = nullptr
Detailed Description
Definition at line 15 of file ultra64.hpp.
Member Function Documentation
load_config()
Json::Value wxUltra64::load_config ()
Definition at line 39 of file ultra64.cpp.
 {
     std::string home_dir(getenv("HOME"));
     std::string config_dir = home_dir + "/" + config_path;
     if(!std::filesystem::is_directory(config_dir))
     {
         std::cout << config_dir << " doesn't exist, creating." << std::endl;
         std::filesystem::create_directory(config_dir);
     }
     std::string config_file_path =  config_dir + "/config.json";
     if(!std::filesystem::exists(config_file_path))
     {
         std::cout << config_file_path << " doesn't exist, creating." << std::endl;
         Json::Value config;
         config["pif_rom_path"] = config_dir;
         if(std::filesystem::exists(config_dir + "/pifdata.bin"))
         {
             config["pif_rom"] = "pifdata.bin";
         }
         else config["pif_rom"] = "";
         config["rom_path"] = home_dir;
         Json::StreamWriterBuilder builder;
         builder["indentation"] = " ";
         std::unique_ptr<Json::StreamWriter> writer(builder.newStreamWriter());
         std::ofstream config_file(config_file_path);
         writer->write(config, &config_file);
         config_file.close();
     }
     Json::Value config;
     std::ifstream config_file(config_file_path);
     config_file >> config;
     return config;
 }
References config, and config_path.
Referenced by OnInit().
OnInit()
bool wxUltra64::OnInit () virtual
Definition at line 18 of file ultra64.cpp.
 {
     this->frame = new MainWindow("Ultra64", wxPoint(20, 20), wxSize(320, 240));
     this->frame->Show(true);
     this->config = this->load_config();
     std::string argv1;
     if(wxGetApp().argc > 1)
     {
         argv1 = wxGetApp().argv[1].ToStdString();
     }
     start(argv1);
     return true;
 }
References config, frame, load_config(), and start().
save_config()
void wxUltra64::save_config ()
Definition at line 81 of file ultra64.cpp.
 {
     std::string home_dir(getenv("HOME"));
     std::string config_dir = home_dir + "/" + config_path;
     std::string config_file_path =  config_dir + "/config.json";
     Json::StreamWriterBuilder builder;
     builder["indentation"] = " ";
     std::unique_ptr<Json::StreamWriter> writer(builder.newStreamWriter());
     std::ofstream config_file(config_file_path);
     writer->write(this->config, &config_file);
     config_file.close();
 }
References config, and config_path.
Member Data Documentation
config
Json::Value wxUltra64::config
Definition at line 23 of file ultra64.hpp.
Referenced by load_config(), OnInit(), and save_config().
config_path
std::string wxUltra64::config_path = ".config/ultra64"
Definition at line 24 of file ultra64.hpp.
Referenced by load_config(), and save_config().
debugger
DebuggerWindow* wxUltra64::debugger = nullptr
Definition at line 21 of file ultra64.hpp.
frame
MainWindow* wxUltra64::frame = nullptr
Definition at line 19 of file ultra64.hpp.
Referenced by OnInit().
n64
ultra64::N64* wxUltra64::n64 = nullptr
Definition at line 22 of file ultra64.hpp.
registers
RegistersWindow* wxUltra64::registers = nullptr
Definition at line 20 of file ultra64.hpp.
The documentation for this class was generated from the following files:
src/ultra64.hpp
src/ultra64.cpp