ultra64: ultra64::N64 Class Reference
ultra64::N64 Class Reference
#include <N64.hpp>
Public Member Functions
N64 ()
void load_pif_rom (std::string filepath)
Public Attributes
vr4300 cpu
MMU * mmu
ROM * rom
RSP rsp
Detailed Description
Definition at line 11 of file N64.hpp.
Constructor & Destructor Documentation
N64()
ultra64::N64::N64 () inline
Definition at line 14 of file N64.hpp.
           {
               this->mmu = new MMU();
               this->cpu.set_n64(this);
               this->rsp.set_n64(this);
           };
References cpu, mmu, rsp, ultra64::RSP::set_n64(), and ultra64::vr4300::set_n64().
Member Function Documentation
load_pif_rom()
void N64::load_pif_rom (std::string filepath)
Definition at line 6 of file N64.cpp.
 {
     ultra64::PIFrom pifrom(filepath);
     uint32_t count = 0;
     uint32_t *p = (uint32_t *)pifrom.get_pointer();
     ultra64::map_memory(this->mmu, "pif_rom", 0x1FC00000, 0x7C0, 0x7C0, new std::byte[0x7C0], nullptr, nullptr);
     while(count < 0x7C0)
     {
         this->mmu->write_word_raw(0x1FC00000 + count, *p++);
         count += 4;
     }
     std::cout << "Loaded " << filepath << std::endl;
 }
References ultra64::PIFrom::get_pointer(), ultra64::map_memory(), mmu, and ultra64::MMU::write_word_raw().
Referenced by load_pif_rom().
Member Data Documentation
cpu
vr4300 ultra64::N64::cpu
Definition at line 21 of file N64.hpp.
Referenced by N64(), DebuggerWindow::OnCPUStep(), render_registers(), and DebuggerWindow::view().
mmu
MMU* ultra64::N64::mmu
Definition at line 20 of file N64.hpp.
Referenced by N64(), load_pif_rom(), ultra64::ROM::Open(), ultra64::RSP::set_n64(), ultra64::vr4300::step(), and DebuggerWindow::view().
rom
ROM* ultra64::N64::rom
Definition at line 23 of file N64.hpp.
Referenced by start().
rsp
RSP ultra64::N64::rsp
Definition at line 22 of file N64.hpp.
Referenced by N64().
The documentation for this class was generated from the following files:
src/n64/N64.hpp
src/n64/N64.cpp