ultra64: DebuggerWindow Class Reference
DebuggerWindow Class Reference
#include <DebuggerWindow.hpp>
Public Member Functions
DebuggerWindow (wxWindow *parent, const wxString &title, const wxPoint &pos, const wxSize &size)
~DebuggerWindow ()
void OnCPUStep (wxCommandEvent &event)
void OnCPUSteps (wxCommandEvent &event)
void view (uint32_t start_addr, uint32_t end_addr)
wxDECLARE_EVENT_TABLE ()
Public Attributes
wxButton * cpu_step = NULL
wxButton * cpu_steps = NULL
wxTextCtrl * cpu_steps_count = NULL
wxTextCtrl * debugger_pc = NULL
wxListBox * memory_listbox = NULL
Detailed Description
Definition at line 4 of file DebuggerWindow.hpp.
Constructor & Destructor Documentation
DebuggerWindow()
DebuggerWindow::DebuggerWindow (wxWindow * parent, const wxString & title, const wxPoint & pos, const wxSize & size)
~DebuggerWindow()
DebuggerWindow::~DebuggerWindow ()
Definition at line 35 of file DebuggerWindow.cpp.
 {
     wxGetApp().debugger = NULL;
 }
Member Function Documentation
OnCPUStep()
void DebuggerWindow::OnCPUStep (wxCommandEvent & event)
Definition at line 40 of file DebuggerWindow.cpp.
 {
     ultra64::N64 *n64 = wxGetApp().n64;
     try
     {
         n64->cpu.step();
     }
     catch(std::string e)
     {
         wxGetApp().frame->SetStatusText(e, 0);
     }
     char message[1024];
     sprintf(message, "0x%.4X %.4X", n64->cpu.get_PC() >> 16, n64->cpu.get_PC() & 0xFFFF);
     debugger_pc->Clear();
     debugger_pc->AppendText(message);
     if(wxGetApp().registers != nullptr) wxGetApp().registers->UpdateRegisters(render_debugger_registers(wxGetApp().n64));
 }
References ultra64::N64::cpu, debugger_pc, ultra64::vr4300::get_PC(), render_debugger_registers(), and ultra64::vr4300::step().
OnCPUSteps()
void DebuggerWindow::OnCPUSteps (wxCommandEvent & event)
Definition at line 61 of file DebuggerWindow.cpp.
 {
     ultra64::N64 *n64 = wxGetApp().n64;
     wxString contents = this->cpu_steps_count->GetValue();
     uint32_t steps = wxAtoi(contents), count = 0;
     char message[1024];
     sprintf(message, "%d", steps);
     cpu_steps_count->Clear();
     cpu_steps_count->AppendText(message);
     while(count < steps)
     {
         try
         {
             n64->cpu.step();
         }
         catch(std::string e)
         {
             wxGetApp().frame->SetStatusText(e, 0);
         }
         count++;
     }
     sprintf(message, "0x%.4X %.4X", n64->cpu.get_PC() >> 16, n64->cpu.get_PC() & 0xFFFF);
     debugger_pc->Clear();
     debugger_pc->AppendText(message);
     if(wxGetApp().registers != NULL) wxGetApp().registers->UpdateRegisters(render_debugger_registers(wxGetApp().n64));
 }
References ultra64::N64::cpu, cpu_steps_count, debugger_pc, ultra64::vr4300::get_PC(), render_debugger_registers(), and ultra64::vr4300::step().
view()
void DebuggerWindow::view (uint32_t start_addr, uint32_t end_addr)
Definition at line 93 of file DebuggerWindow.cpp.
 {
     ultra64::N64 *n64 = wxGetApp().n64;
     char message[1024];
     std::string msg;
     uint32_t value, addr = start_addr;
     sprintf(message, "0x%.4X %.4X", n64->cpu.get_PC() >> 16, n64->cpu.get_PC() & 0xFFFF);
     this->debugger_pc->Clear();
     this->debugger_pc->AppendText(message);
     while(addr < end_addr)
     {
         try
         {
             value = n64->mmu->read_word(addr);
             sprintf(message, "%.4X %.4X   %.2X %.2X %.2X %.2X   ", (addr >> 16), (addr & 0xFFFF),
                    value >> 24, (value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF);
             ultra64::instruction i(value);
             msg = message + i.to_string();
             memory_listbox->Append(msg.c_str());
         }
         catch(std::string e)
         {
             memory_listbox->Append(e.c_str());
             return;
         }
         addr += 4;
     }
 }
References ultra64::N64::cpu, debugger_pc, ultra64::vr4300::get_PC(), memory_listbox, ultra64::N64::mmu, ultra64::MMU::read_word(), and ultra64::instruction::to_string().
wxDECLARE_EVENT_TABLE()
DebuggerWindow::wxDECLARE_EVENT_TABLE ()
Member Data Documentation
cpu_step
wxButton* DebuggerWindow::cpu_step = NULL
Definition at line 12 of file DebuggerWindow.hpp.
cpu_steps
wxButton* DebuggerWindow::cpu_steps = NULL
Definition at line 15 of file DebuggerWindow.hpp.
cpu_steps_count
wxTextCtrl* DebuggerWindow::cpu_steps_count = NULL
Definition at line 14 of file DebuggerWindow.hpp.
Referenced by OnCPUSteps().
debugger_pc
wxTextCtrl* DebuggerWindow::debugger_pc = NULL
Definition at line 11 of file DebuggerWindow.hpp.
Referenced by OnCPUStep(), OnCPUSteps(), and view().
memory_listbox
wxListBox* DebuggerWindow::memory_listbox = NULL
Definition at line 9 of file DebuggerWindow.hpp.
Referenced by view().
The documentation for this class was generated from the following files:
src/DebuggerWindow.hpp
src/DebuggerWindow.cpp