ultra64: CRC Class Reference
CRC Class Reference
Static class for computing CRCs.
#include <CRC.h>
Classes
struct Parameters
CRC parameters.
struct Table
CRC lookup table. After construction, the CRC parameters are fixed.
Static Public Member Functions
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType Calculate (const void *data, crcpp_size size, const Parameters< CRCType, CRCWidth > &parameters)
Computes a CRC.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType Calculate (const void *data, crcpp_size size, const Parameters< CRCType, CRCWidth > &parameters, CRCType crc)
Appends additional data to a previous CRC calculation.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType Calculate (const void *data, crcpp_size size, const Table< CRCType, CRCWidth > &lookupTable)
Computes a CRC via a lookup table.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType Calculate (const void *data, crcpp_size size, const Table< CRCType, CRCWidth > &lookupTable, CRCType crc)
Appends additional data to a previous CRC calculation using a lookup table.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType CalculateBits (const void *data, crcpp_size size, const Parameters< CRCType, CRCWidth > &parameters)
Computes a CRC.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType CalculateBits (const void *data, crcpp_size size, const Parameters< CRCType, CRCWidth > &parameters, CRCType crc)
Appends additional data to a previous CRC calculation.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType CalculateBits (const void *data, crcpp_size size, const Table< CRCType, CRCWidth > &lookupTable)
Computes a CRC via a lookup table.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType CalculateBits (const void *data, crcpp_size size, const Table< CRCType, CRCWidth > &lookupTable, CRCType crc)
Appends additional data to a previous CRC calculation using a lookup table.
static const Parameters< crcpp_uint16, 16 > & CRC_16_ARC ()
Returns a set of parameters for CRC-16 ARC (aka CRC-16 IBM, CRC-16 LHA).
static const Parameters< crcpp_uint16, 16 > & CRC_16_BUYPASS ()
Returns a set of parameters for CRC-16 BUYPASS (aka CRC-16 VERIFONE, CRC-16 UMTS).
static const Parameters< crcpp_uint16, 16 > & CRC_16_CCITTFALSE ()
Returns a set of parameters for CRC-16 CCITT FALSE.
static const Parameters< crcpp_uint16, 16 > & CRC_16_GENIBUS ()
Returns a set of parameters for CRC-16 GENIBUS (aka CRC-16 EPC, CRC-16 I-CODE, CRC-16 DARC).
static const Parameters< crcpp_uint16, 16 > & CRC_16_KERMIT ()
Returns a set of parameters for CRC-16 KERMIT (aka CRC-16 CCITT, CRC-16 CCITT-TRUE).
static const Parameters< crcpp_uint16, 16 > & CRC_16_X25 ()
Returns a set of parameters for CRC-16 X-25 (aka CRC-16 IBM-SDLC, CRC-16 ISO-HDLC, CRC-16 B).
static const Parameters< crcpp_uint16, 16 > & CRC_16_XMODEM ()
Returns a set of parameters for CRC-16 XMODEM (aka CRC-16 ZMODEM, CRC-16 ACORN, CRC-16 LTE).
static const Parameters< crcpp_uint32, 32 > & CRC_32 ()
Returns a set of parameters for CRC-32 (aka CRC-32 ADCCP, CRC-32 PKZip).
static const Parameters< crcpp_uint32, 32 > & CRC_32_BZIP2 ()
Returns a set of parameters for CRC-32 BZIP2 (aka CRC-32 AAL5, CRC-32 DECT-B, CRC-32 B-CRC).
static const Parameters< crcpp_uint32, 32 > & CRC_32_MPEG2 ()
Returns a set of parameters for CRC-32 MPEG-2.
static const Parameters< crcpp_uint32, 32 > & CRC_32_POSIX ()
Returns a set of parameters for CRC-32 POSIX.
static const Parameters< crcpp_uint8, 8 > & CRC_8 ()
Returns a set of parameters for CRC-8 SMBus.
Private Member Functions
CRC ()
CRC (const CRC &other)
CRC & operator= (const CRC &other)
Static Private Member Functions
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType CalculateRemainder (const void *data, crcpp_size size, const Parameters< CRCType, CRCWidth > &parameters, CRCType remainder)
Computes a CRC remainder.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType CalculateRemainder (const void *data, crcpp_size size, const Table< CRCType, CRCWidth > &lookupTable, CRCType remainder)
Computes a CRC remainder using lookup table.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType CalculateRemainderBits (unsigned char byte, crcpp_size numBits, const Parameters< CRCType, CRCWidth > &parameters, CRCType remainder)
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType Finalize (CRCType remainder, CRCType finalXOR, bool reflectOutput)
Computes the final reflection and XOR of a CRC remainder.
template<typename IntegerType >
static IntegerType Reflect (IntegerType value, crcpp_uint16 numBits)
Reflects (i.e. reverses the bits within) an integer value.
template<typename CRCType , crcpp_uint16 CRCWidth>
static CRCType UndoFinalize (CRCType remainder, CRCType finalXOR, bool reflectOutput)
Undoes the process of computing the final reflection and XOR of a CRC remainder.
Detailed Description
Static class for computing CRCs.
Note
This class supports computation of full and multi-part CRCs, using a bit-by-bit algorithm or a byte-by-byte lookup table. The CRCs are calculated using as many optimizations as is reasonable. If compiling with C++11, the constexpr keyword is used liberally so that many calculations are performed at compile-time instead of at runtime.
Definition at line 142 of file CRC.h.
Constructor & Destructor Documentation
CRC() [1/2]
CRC::CRC () private
CRC() [2/2]
CRC::CRC (const CRC & other) private
Member Function Documentation
Calculate() [1/4]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::Calculate (const void * data, crcpp_size size, const Parameters< CRCType, CRCWidth > & parameters) inline static
Computes a CRC.
Parameters
[in] data Data over which CRC will be computed
[in] size Size of the data, in bytes
[in] parameters CRC parameters
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC
Definition at line 455 of file CRC.h.
 {
     CRCType remainder = CalculateRemainder(data, size, parameters, parameters.initialValue);
     // No need to mask the remainder here; the mask will be applied in the Finalize() function.
     return Finalize<CRCType, CRCWidth>(remainder, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
 }
References CalculateRemainder(), CRC::Parameters< CRCType, CRCWidth >::finalXOR, CRC::Parameters< CRCType, CRCWidth >::initialValue, CRC::Parameters< CRCType, CRCWidth >::reflectInput, and CRC::Parameters< CRCType, CRCWidth >::reflectOutput.
Referenced by start().
Calculate() [2/4]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::Calculate (const void * data, crcpp_size size, const Parameters< CRCType, CRCWidth > & parameters, CRCType crc) inline static
Appends additional data to a previous CRC calculation.
Note
This function can be used to compute multi-part CRCs.
Parameters
[in] data Data over which CRC will be computed
[in] size Size of the data, in bytes
[in] parameters CRC parameters
[in] crc CRC from a previous calculation
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC
Definition at line 475 of file CRC.h.
 {
     CRCType remainder = UndoFinalize<CRCType, CRCWidth>(crc, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
     remainder = CalculateRemainder(data, size, parameters, remainder);
     // No need to mask the remainder here; the mask will be applied in the Finalize() function.
     return Finalize<CRCType, CRCWidth>(remainder, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
 }
References CalculateRemainder(), CRC::Parameters< CRCType, CRCWidth >::finalXOR, CRC::Parameters< CRCType, CRCWidth >::reflectInput, and CRC::Parameters< CRCType, CRCWidth >::reflectOutput.
Calculate() [3/4]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::Calculate (const void * data, crcpp_size size, const Table< CRCType, CRCWidth > & lookupTable) inline static
Computes a CRC via a lookup table.
Parameters
[in] data Data over which CRC will be computed
[in] size Size of the data, in bytes
[in] lookupTable CRC lookup table
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC
Definition at line 496 of file CRC.h.
 {
     const Parameters<CRCType, CRCWidth> & parameters = lookupTable.GetParameters();
     CRCType remainder = CalculateRemainder(data, size, lookupTable, parameters.initialValue);
     // No need to mask the remainder here; the mask will be applied in the Finalize() function.
     return Finalize<CRCType, CRCWidth>(remainder, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
 }
References CalculateRemainder(), CRC::Parameters< CRCType, CRCWidth >::finalXOR, CRC::Table< CRCType, CRCWidth >::GetParameters(), CRC::Parameters< CRCType, CRCWidth >::initialValue, CRC::Parameters< CRCType, CRCWidth >::reflectInput, and CRC::Parameters< CRCType, CRCWidth >::reflectOutput.
Calculate() [4/4]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::Calculate (const void * data, crcpp_size size, const Table< CRCType, CRCWidth > & lookupTable, CRCType crc) inline static
Appends additional data to a previous CRC calculation using a lookup table.
Note
This function can be used to compute multi-part CRCs.
Parameters
[in] data Data over which CRC will be computed
[in] size Size of the data, in bytes
[in] lookupTable CRC lookup table
[in] crc CRC from a previous calculation
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC
Definition at line 519 of file CRC.h.
 {
     const Parameters<CRCType, CRCWidth> & parameters = lookupTable.GetParameters();
     CRCType remainder = UndoFinalize<CRCType, CRCWidth>(crc, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
     remainder = CalculateRemainder(data, size, lookupTable, remainder);
     // No need to mask the remainder here; the mask will be applied in the Finalize() function.
     return Finalize<CRCType, CRCWidth>(remainder, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
 }
References CalculateRemainder(), CRC::Parameters< CRCType, CRCWidth >::finalXOR, CRC::Table< CRCType, CRCWidth >::GetParameters(), CRC::Parameters< CRCType, CRCWidth >::reflectInput, and CRC::Parameters< CRCType, CRCWidth >::reflectOutput.
CalculateBits() [1/4]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::CalculateBits (const void * data, crcpp_size size, const Parameters< CRCType, CRCWidth > & parameters) inline static
Computes a CRC.
Parameters
[in] data Data over which CRC will be computed
[in] size Size of the data, in bits
[in] parameters CRC parameters
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC
Definition at line 542 of file CRC.h.
 {
     CRCType remainder = parameters.initialValue;
     // Calculate the remainder on a whole number of bytes first, then call
     // a special-case function for the remaining bits.
     crcpp_size wholeNumberOfBytes = size / CHAR_BIT;
     if (wholeNumberOfBytes > 0)
     {
         remainder = CalculateRemainder(data, wholeNumberOfBytes, parameters, remainder);
     }
     crcpp_size remainingNumberOfBits = size % CHAR_BIT;
     if (remainingNumberOfBits != 0)
     {
         unsigned char lastByte = *(reinterpret_cast<const unsigned char *>(data) + wholeNumberOfBytes);
         remainder = CalculateRemainderBits(lastByte, remainingNumberOfBits, parameters, remainder);
     }
     // No need to mask the remainder here; the mask will be applied in the Finalize() function.
     return Finalize<CRCType, CRCWidth>(remainder, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
 }
References CalculateRemainder(), CalculateRemainderBits(), crcpp_size, CRC::Parameters< CRCType, CRCWidth >::finalXOR, CRC::Parameters< CRCType, CRCWidth >::initialValue, CRC::Parameters< CRCType, CRCWidth >::reflectInput, and CRC::Parameters< CRCType, CRCWidth >::reflectOutput.
CalculateBits() [2/4]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::CalculateBits (const void * data, crcpp_size size, const Parameters< CRCType, CRCWidth > & parameters, CRCType crc) inline static
Appends additional data to a previous CRC calculation.
Note
This function can be used to compute multi-part CRCs.
Parameters
[in] data Data over which CRC will be computed
[in] size Size of the data, in bits
[in] parameters CRC parameters
[in] crc CRC from a previous calculation
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC
Definition at line 577 of file CRC.h.
 {
     CRCType remainder = UndoFinalize<CRCType, CRCWidth>(crc, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
     // Calculate the remainder on a whole number of bytes first, then call
     // a special-case function for the remaining bits.
     crcpp_size wholeNumberOfBytes = size / CHAR_BIT;
     if (wholeNumberOfBytes > 0)
     {
         remainder = CalculateRemainder(data, wholeNumberOfBytes, parameters, parameters.initialValue);
     }
     crcpp_size remainingNumberOfBits = size % CHAR_BIT;
     if (remainingNumberOfBits != 0)
     {
         unsigned char lastByte = *(reinterpret_cast<const unsigned char *>(data) + wholeNumberOfBytes);
         remainder = CalculateRemainderBits(lastByte, remainingNumberOfBits, parameters, remainder);
     }
     // No need to mask the remainder here; the mask will be applied in the Finalize() function.
     return Finalize<CRCType, CRCWidth>(remainder, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
 }
References CalculateRemainder(), CalculateRemainderBits(), crcpp_size, CRC::Parameters< CRCType, CRCWidth >::finalXOR, CRC::Parameters< CRCType, CRCWidth >::initialValue, CRC::Parameters< CRCType, CRCWidth >::reflectInput, and CRC::Parameters< CRCType, CRCWidth >::reflectOutput.
CalculateBits() [3/4]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::CalculateBits (const void * data, crcpp_size size, const Table< CRCType, CRCWidth > & lookupTable) inline static
Computes a CRC via a lookup table.
Parameters
[in] data Data over which CRC will be computed
[in] size Size of the data, in bits
[in] lookupTable CRC lookup table
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC
Definition at line 611 of file CRC.h.
 {
     const Parameters<CRCType, CRCWidth> & parameters = lookupTable.GetParameters();
     CRCType remainder = parameters.initialValue;
     // Calculate the remainder on a whole number of bytes first, then call
     // a special-case function for the remaining bits.
     crcpp_size wholeNumberOfBytes = size / CHAR_BIT;
     if (wholeNumberOfBytes > 0)
     {
         remainder = CalculateRemainder(data, wholeNumberOfBytes, lookupTable, remainder);
     }
     crcpp_size remainingNumberOfBits = size % CHAR_BIT;
     if (remainingNumberOfBits != 0)
     {
         unsigned char lastByte = *(reinterpret_cast<const unsigned char *>(data) + wholeNumberOfBytes);
         remainder = CalculateRemainderBits(lastByte, remainingNumberOfBits, parameters, remainder);
     }
     // No need to mask the remainder here; the mask will be applied in the Finalize() function.
     return Finalize<CRCType, CRCWidth>(remainder, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
 }
References CalculateRemainder(), CalculateRemainderBits(), crcpp_size, CRC::Parameters< CRCType, CRCWidth >::finalXOR, CRC::Table< CRCType, CRCWidth >::GetParameters(), CRC::Parameters< CRCType, CRCWidth >::initialValue, CRC::Parameters< CRCType, CRCWidth >::reflectInput, and CRC::Parameters< CRCType, CRCWidth >::reflectOutput.
CalculateBits() [4/4]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::CalculateBits (const void * data, crcpp_size size, const Table< CRCType, CRCWidth > & lookupTable, CRCType crc) inline static
Appends additional data to a previous CRC calculation using a lookup table.
Note
This function can be used to compute multi-part CRCs.
Parameters
[in] data Data over which CRC will be computed
[in] size Size of the data, in bits
[in] lookupTable CRC lookup table
[in] crc CRC from a previous calculation
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC
Definition at line 649 of file CRC.h.
 {
     const Parameters<CRCType, CRCWidth> & parameters = lookupTable.GetParameters();
     CRCType remainder = UndoFinalize<CRCType, CRCWidth>(crc, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
     // Calculate the remainder on a whole number of bytes first, then call
     // a special-case function for the remaining bits.
     crcpp_size wholeNumberOfBytes = size / CHAR_BIT;
     if (wholeNumberOfBytes > 0)
     {
         remainder = CalculateRemainder(data, wholeNumberOfBytes, lookupTable, parameters.initialValue);
     }
     crcpp_size remainingNumberOfBits = size % CHAR_BIT;
     if (remainingNumberOfBits > 0)
     {
         unsigned char lastByte = *(reinterpret_cast<const unsigned char *>(data) + wholeNumberOfBytes);
         remainder = CalculateRemainderBits(lastByte, remainingNumberOfBits, parameters, remainder);
     }
     // No need to mask the remainder here; the mask will be applied in the Finalize() function.
     return Finalize<CRCType, CRCWidth>(remainder, parameters.finalXOR, parameters.reflectInput != parameters.reflectOutput);
 }
References CalculateRemainder(), CalculateRemainderBits(), crcpp_size, CRC::Parameters< CRCType, CRCWidth >::finalXOR, CRC::Table< CRCType, CRCWidth >::GetParameters(), CRC::Parameters< CRCType, CRCWidth >::initialValue, CRC::Parameters< CRCType, CRCWidth >::reflectInput, and CRC::Parameters< CRCType, CRCWidth >::reflectOutput.
CalculateRemainder() [1/2]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::CalculateRemainder (const void * data, crcpp_size size, const Parameters< CRCType, CRCWidth > & parameters, CRCType remainder) inline static private
Computes a CRC remainder.
Parameters
[in] data Data over which the remainder will be computed
[in] size Size of the data, in bytes
[in] parameters CRC parameters
[in] remainder Running CRC remainder. Can be an initial value or the result of a previous CRC remainder calculation.
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC remainder
Definition at line 765 of file CRC.h.
 {
 #ifdef CRCPP_USE_CPP11
     // This static_assert is put here because this function will always be compiled in no matter what
     // the template parameters are and whether or not a table lookup or bit-by-bit algorithm is used.
     static_assert(::std::numeric_limits<CRCType>::digits >= CRCWidth, "CRCType is too small to contain a CRC of width CRCWidth.");
 #else
     // Catching this compile-time error is very important. Sadly, the compiler error will be very cryptic, but it's
     // better than nothing.
     enum { static_assert_failed_CRCType_is_too_small_to_contain_a_CRC_of_width_CRCWidth = 1 / (::std::numeric_limits<CRCType>::digits >= CRCWidth ? 1 : 0) };
 #endif
     const unsigned char * current = reinterpret_cast<const unsigned char *>(data);
     // Slightly different implementations based on the parameters. The current implementations try to eliminate as much
     // computation from the inner loop (looping over each bit) as possible.
     if (parameters.reflectInput)
     {
         CRCType polynomial = CRC::Reflect(parameters.polynomial, CRCWidth);
         while (size--)
         {
             remainder = static_cast<CRCType>(remainder ^ *current++);
             // An optimizing compiler might choose to unroll this loop.
             for (crcpp_size i = 0; i < CHAR_BIT; ++i)
             {
 #ifdef CRCPP_BRANCHLESS
                 // Clever way to avoid a branch at the expense of a multiplication. This code is equivalent to the following:
                 // if (remainder & 1)
                 //     remainder = (remainder >> 1) ^ polynomial;
                 // else
                 //     remainder >>= 1;
                 remainder = static_cast<CRCType>((remainder >> 1) ^ ((remainder & 1) * polynomial));
 #else
                 remainder = static_cast<CRCType>((remainder & 1) ? ((remainder >> 1) ^ polynomial) : (remainder >> 1));
 #endif
             }
         }
     }
     else if (CRCWidth >= CHAR_BIT)
     {
         static crcpp_constexpr CRCType CRC_WIDTH_MINUS_ONE(CRCWidth - CRCType(1));
 #ifndef CRCPP_BRANCHLESS
         static crcpp_constexpr CRCType CRC_HIGHEST_BIT_MASK(CRCType(1) << CRC_WIDTH_MINUS_ONE);
 #endif
         // The conditional expression is used to avoid a -Wshift-count-overflow warning.
         static crcpp_constexpr CRCType SHIFT((CRCWidth >= CHAR_BIT) ? static_cast<CRCType>(CRCWidth - CHAR_BIT) : 0);
         while (size--)
         {
             remainder = static_cast<CRCType>(remainder ^ (static_cast<CRCType>(*current++) << SHIFT));
             // An optimizing compiler might choose to unroll this loop.
             for (crcpp_size i = 0; i < CHAR_BIT; ++i)
             {
 #ifdef CRCPP_BRANCHLESS
                 // Clever way to avoid a branch at the expense of a multiplication. This code is equivalent to the following:
                 // if (remainder & CRC_HIGHEST_BIT_MASK)
                 //     remainder = (remainder << 1) ^ parameters.polynomial;
                 // else
                 //     remainder <<= 1;
                 remainder = static_cast<CRCType>((remainder << 1) ^ (((remainder >> CRC_WIDTH_MINUS_ONE) & 1) * parameters.polynomial));
 #else
                 remainder = static_cast<CRCType>((remainder & CRC_HIGHEST_BIT_MASK) ? ((remainder << 1) ^ parameters.polynomial) : (remainder << 1));
 #endif
             }
         }
     }
     else
     {
         static crcpp_constexpr CRCType CHAR_BIT_MINUS_ONE(CHAR_BIT - 1);
 #ifndef CRCPP_BRANCHLESS
         static crcpp_constexpr CRCType CHAR_BIT_HIGHEST_BIT_MASK(CRCType(1) << CHAR_BIT_MINUS_ONE);
 #endif
         // The conditional expression is used to avoid a -Wshift-count-overflow warning.
         static crcpp_constexpr CRCType SHIFT((CHAR_BIT >= CRCWidth) ? static_cast<CRCType>(CHAR_BIT - CRCWidth) : 0);
         CRCType polynomial = static_cast<CRCType>(parameters.polynomial << SHIFT);
         remainder = static_cast<CRCType>(remainder << SHIFT);
         while (size--)
         {
             remainder = static_cast<CRCType>(remainder ^ *current++);
             // An optimizing compiler might choose to unroll this loop.
             for (crcpp_size i = 0; i < CHAR_BIT; ++i)
             {
 #ifdef CRCPP_BRANCHLESS
                 // Clever way to avoid a branch at the expense of a multiplication. This code is equivalent to the following:
                 // if (remainder & CHAR_BIT_HIGHEST_BIT_MASK)
                 //     remainder = (remainder << 1) ^ polynomial;
                 // else
                 //     remainder <<= 1;
                 remainder = static_cast<CRCType>((remainder << 1) ^ (((remainder >> CHAR_BIT_MINUS_ONE) & 1) * polynomial));
 #else
                 remainder = static_cast<CRCType>((remainder & CHAR_BIT_HIGHEST_BIT_MASK) ? ((remainder << 1) ^ polynomial) : (remainder << 1));
 #endif
             }
         }
         remainder = static_cast<CRCType>(remainder >> SHIFT);
     }
     return remainder;
 }
References crcpp_constexpr, crcpp_size, CRC::Parameters< CRCType, CRCWidth >::polynomial, Reflect(), and CRC::Parameters< CRCType, CRCWidth >::reflectInput.
Referenced by Calculate(), and CalculateBits().
CalculateRemainder() [2/2]
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::CalculateRemainder (const void * data, crcpp_size size, const Table< CRCType, CRCWidth > & lookupTable, CRCType remainder) inline static private
Computes a CRC remainder using lookup table.
Parameters
[in] data Data over which the remainder will be computed
[in] size Size of the data, in bytes
[in] lookupTable CRC lookup table
[in] remainder Running CRC remainder. Can be an initial value or the result of a previous CRC remainder calculation.
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC remainder
Definition at line 882 of file CRC.h.
 {
     const unsigned char * current = reinterpret_cast<const unsigned char *>(data);
     if (lookupTable.GetParameters().reflectInput)
     {
         while (size--)
         {
 #if defined(WIN32) || defined(_WIN32) || defined(WINCE)
     // Disable warning about data loss when doing (remainder >> CHAR_BIT) when
     // remainder is one byte long. The algorithm is still correct in this case,
     // though it's possible that one additional machine instruction will be executed.
 #   pragma warning (push)
 #   pragma warning (disable : 4333)
 #endif
             remainder = static_cast<CRCType>((remainder >> CHAR_BIT) ^ lookupTable[static_cast<unsigned char>(remainder ^ *current++)]);
 #if defined(WIN32) || defined(_WIN32) || defined(WINCE)
 #   pragma warning (pop)
 #endif
         }
     }
     else if (CRCWidth >= CHAR_BIT)
     {
         // The conditional expression is used to avoid a -Wshift-count-overflow warning.
         static crcpp_constexpr CRCType SHIFT((CRCWidth >= CHAR_BIT) ? static_cast<CRCType>(CRCWidth - CHAR_BIT) : 0);
         while (size--)
         {
             remainder = static_cast<CRCType>((remainder << CHAR_BIT) ^ lookupTable[static_cast<unsigned char>((remainder >> SHIFT) ^ *current++)]);
         }
     }
     else
     {
         // The conditional expression is used to avoid a -Wshift-count-overflow warning.
         static crcpp_constexpr CRCType SHIFT((CHAR_BIT >= CRCWidth) ? static_cast<CRCType>(CHAR_BIT - CRCWidth) : 0);
         remainder = static_cast<CRCType>(remainder << SHIFT);
         while (size--)
         {
             // Note: no need to mask here since remainder is guaranteed to fit in a single byte.
             remainder = lookupTable[static_cast<unsigned char>(remainder ^ *current++)];
         }
         remainder = static_cast<CRCType>(remainder >> SHIFT);
     }
     return remainder;
 }
References crcpp_constexpr, and CRC::Table< CRCType, CRCWidth >::GetParameters().
CalculateRemainderBits()
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::CalculateRemainderBits (unsigned char byte, crcpp_size numBits, const Parameters< CRCType, CRCWidth > & parameters, CRCType remainder) inline static private
Definition at line 933 of file CRC.h.
 {
     // Slightly different implementations based on the parameters. The current implementations try to eliminate as much
     // computation from the inner loop (looping over each bit) as possible.
     if (parameters.reflectInput)
     {
         CRCType polynomial = CRC::Reflect(parameters.polynomial, CRCWidth);
         remainder = static_cast<CRCType>(remainder ^ byte);
         // An optimizing compiler might choose to unroll this loop.
         for (crcpp_size i = 0; i < numBits; ++i)
         {
 #ifdef CRCPP_BRANCHLESS
             // Clever way to avoid a branch at the expense of a multiplication. This code is equivalent to the following:
             // if (remainder & 1)
             //     remainder = (remainder >> 1) ^ polynomial;
             // else
             //     remainder >>= 1;
             remainder = static_cast<CRCType>((remainder >> 1) ^ ((remainder & 1) * polynomial));
 #else
             remainder = static_cast<CRCType>((remainder & 1) ? ((remainder >> 1) ^ polynomial) : (remainder >> 1));
 #endif
         }
     }
     else if (CRCWidth >= CHAR_BIT)
     {
         static crcpp_constexpr CRCType CRC_WIDTH_MINUS_ONE(CRCWidth - CRCType(1));
 #ifndef CRCPP_BRANCHLESS
         static crcpp_constexpr CRCType CRC_HIGHEST_BIT_MASK(CRCType(1) << CRC_WIDTH_MINUS_ONE);
 #endif
         // The conditional expression is used to avoid a -Wshift-count-overflow warning.
         static crcpp_constexpr CRCType SHIFT((CRCWidth >= CHAR_BIT) ? static_cast<CRCType>(CRCWidth - CHAR_BIT) : 0);
         remainder = static_cast<CRCType>(remainder ^ (static_cast<CRCType>(byte) << SHIFT));
         // An optimizing compiler might choose to unroll this loop.
         for (crcpp_size i = 0; i < numBits; ++i)
         {
 #ifdef CRCPP_BRANCHLESS
             // Clever way to avoid a branch at the expense of a multiplication. This code is equivalent to the following:
             // if (remainder & CRC_HIGHEST_BIT_MASK)
             //     remainder = (remainder << 1) ^ parameters.polynomial;
             // else
             //     remainder <<= 1;
             remainder = static_cast<CRCType>((remainder << 1) ^ (((remainder >> CRC_WIDTH_MINUS_ONE) & 1) * parameters.polynomial));
 #else
             remainder = static_cast<CRCType>((remainder & CRC_HIGHEST_BIT_MASK) ? ((remainder << 1) ^ parameters.polynomial) : (remainder << 1));
 #endif
         }
     }
     else
     {
         static crcpp_constexpr CRCType CHAR_BIT_MINUS_ONE(CHAR_BIT - 1);
 #ifndef CRCPP_BRANCHLESS
         static crcpp_constexpr CRCType CHAR_BIT_HIGHEST_BIT_MASK(CRCType(1) << CHAR_BIT_MINUS_ONE);
 #endif
         // The conditional expression is used to avoid a -Wshift-count-overflow warning.
         static crcpp_constexpr CRCType SHIFT((CHAR_BIT >= CRCWidth) ? static_cast<CRCType>(CHAR_BIT - CRCWidth) : 0);
         CRCType polynomial = static_cast<CRCType>(parameters.polynomial << SHIFT);
         remainder = static_cast<CRCType>((remainder << SHIFT) ^ byte);
         // An optimizing compiler might choose to unroll this loop.
         for (crcpp_size i = 0; i < numBits; ++i)
         {
 #ifdef CRCPP_BRANCHLESS
             // Clever way to avoid a branch at the expense of a multiplication. This code is equivalent to the following:
             // if (remainder & CHAR_BIT_HIGHEST_BIT_MASK)
             //     remainder = (remainder << 1) ^ polynomial;
             // else
             //     remainder <<= 1;
             remainder = static_cast<CRCType>((remainder << 1) ^ (((remainder >> CHAR_BIT_MINUS_ONE) & 1) * polynomial));
 #else
             remainder = static_cast<CRCType>((remainder & CHAR_BIT_HIGHEST_BIT_MASK) ? ((remainder << 1) ^ polynomial) : (remainder << 1));
 #endif
         }
         remainder = static_cast<CRCType>(remainder >> SHIFT);
     }
     return remainder;
 }
References crcpp_constexpr, crcpp_size, CRC::Parameters< CRCType, CRCWidth >::polynomial, Reflect(), and CRC::Parameters< CRCType, CRCWidth >::reflectInput.
Referenced by CalculateBits().
CRC_16_ARC()
const CRC::Parameters< crcpp_uint16, 16 > & CRC::CRC_16_ARC () inline static
Returns a set of parameters for CRC-16 ARC (aka CRC-16 IBM, CRC-16 LHA).
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-16 ARC has the following parameters and check value:
polynomial = 0x8005
initial value = 0x0000
final XOR = 0x0000
reflect input = true
reflect output = true
check value = 0xBB3D
Returns
CRC-16 ARC parameters
Definition at line 1466 of file CRC.h.
 {
     static const Parameters<crcpp_uint16, 16> parameters = { 0x8005, 0x0000, 0x0000, true, true };
     return parameters;
 }
CRC_16_BUYPASS()
const CRC::Parameters< crcpp_uint16, 16 > & CRC::CRC_16_BUYPASS () inline static
Returns a set of parameters for CRC-16 BUYPASS (aka CRC-16 VERIFONE, CRC-16 UMTS).
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-16 BUYPASS has the following parameters and check value:
polynomial = 0x8005
initial value = 0x0000
final XOR = 0x0000
reflect input = false
reflect output = false
check value = 0xFEE8
Returns
CRC-16 BUYPASS parameters
Definition at line 1484 of file CRC.h.
 {
     static const Parameters<crcpp_uint16, 16> parameters = { 0x8005, 0x0000, 0x0000, false, false };
     return parameters;
 }
CRC_16_CCITTFALSE()
const CRC::Parameters< crcpp_uint16, 16 > & CRC::CRC_16_CCITTFALSE () inline static
Returns a set of parameters for CRC-16 CCITT FALSE.
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-16 CCITT FALSE has the following parameters and check value:
polynomial = 0x1021
initial value = 0xFFFF
final XOR = 0x0000
reflect input = false
reflect output = false
check value = 0x29B1
Returns
CRC-16 CCITT FALSE parameters
Definition at line 1502 of file CRC.h.
 {
     static const Parameters<crcpp_uint16, 16> parameters = { 0x1021, 0xFFFF, 0x0000, false, false };
     return parameters;
 }
CRC_16_GENIBUS()
const CRC::Parameters< crcpp_uint16, 16 > & CRC::CRC_16_GENIBUS () inline static
Returns a set of parameters for CRC-16 GENIBUS (aka CRC-16 EPC, CRC-16 I-CODE, CRC-16 DARC).
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-16 GENIBUS has the following parameters and check value:
polynomial = 0x1021
initial value = 0xFFFF
final XOR = 0xFFFF
reflect input = false
reflect output = false
check value = 0xD64E
Returns
CRC-16 GENIBUS parameters
Definition at line 1612 of file CRC.h.
 {
     static const Parameters<crcpp_uint16, 16> parameters = { 0x1021, 0xFFFF, 0xFFFF, false, false };
     return parameters;
 }
CRC_16_KERMIT()
const CRC::Parameters< crcpp_uint16, 16 > & CRC::CRC_16_KERMIT () inline static
Returns a set of parameters for CRC-16 KERMIT (aka CRC-16 CCITT, CRC-16 CCITT-TRUE).
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-16 KERMIT has the following parameters and check value:
polynomial = 0x1021
initial value = 0x0000
final XOR = 0x0000
reflect input = true
reflect output = true
check value = 0x2189
Returns
CRC-16 KERMIT parameters
Definition at line 1630 of file CRC.h.
 {
     static const Parameters<crcpp_uint16, 16> parameters = { 0x1021, 0x0000, 0x0000, true, true };
     return parameters;
 }
CRC_16_X25()
const CRC::Parameters< crcpp_uint16, 16 > & CRC::CRC_16_X25 () inline static
Returns a set of parameters for CRC-16 X-25 (aka CRC-16 IBM-SDLC, CRC-16 ISO-HDLC, CRC-16 B).
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-16 X-25 has the following parameters and check value:
polynomial = 0x1021
initial value = 0xFFFF
final XOR = 0xFFFF
reflect input = true
reflect output = true
check value = 0x906E
Returns
CRC-16 X-25 parameters
Definition at line 1723 of file CRC.h.
 {
     static const Parameters<crcpp_uint16, 16> parameters = { 0x1021, 0xFFFF, 0xFFFF, true, true };
     return parameters;
 }
CRC_16_XMODEM()
const CRC::Parameters< crcpp_uint16, 16 > & CRC::CRC_16_XMODEM () inline static
Returns a set of parameters for CRC-16 XMODEM (aka CRC-16 ZMODEM, CRC-16 ACORN, CRC-16 LTE).
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-16 XMODEM has the following parameters and check value:
polynomial = 0x1021
initial value = 0x0000
final XOR = 0x0000
reflect input = false
reflect output = false
check value = 0x31C3
Returns
CRC-16 XMODEM parameters
Definition at line 1741 of file CRC.h.
 {
     static const Parameters<crcpp_uint16, 16> parameters = { 0x1021, 0x0000, 0x0000, false, false };
     return parameters;
 }
CRC_32()
const CRC::Parameters< crcpp_uint32, 32 > & CRC::CRC_32 () inline static
Returns a set of parameters for CRC-32 (aka CRC-32 ADCCP, CRC-32 PKZip).
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-32 has the following parameters and check value:
polynomial = 0x04C11DB7
initial value = 0xFFFFFFFF
final XOR = 0xFFFFFFFF
reflect input = true
reflect output = true
check value = 0xCBF43926
Returns
CRC-32 parameters
Definition at line 1926 of file CRC.h.
 {
     static const Parameters<crcpp_uint32, 32> parameters = { 0x04C11DB7, 0xFFFFFFFF, 0xFFFFFFFF, true, true };
     return parameters;
 }
Referenced by start().
CRC_32_BZIP2()
const CRC::Parameters< crcpp_uint32, 32 > & CRC::CRC_32_BZIP2 () inline static
Returns a set of parameters for CRC-32 BZIP2 (aka CRC-32 AAL5, CRC-32 DECT-B, CRC-32 B-CRC).
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-32 BZIP2 has the following parameters and check value:
polynomial = 0x04C11DB7
initial value = 0xFFFFFFFF
final XOR = 0xFFFFFFFF
reflect input = false
reflect output = false
check value = 0xFC891918
Returns
CRC-32 BZIP2 parameters
Definition at line 1944 of file CRC.h.
 {
     static const Parameters<crcpp_uint32, 32> parameters = { 0x04C11DB7, 0xFFFFFFFF, 0xFFFFFFFF, false, false };
     return parameters;
 }
CRC_32_MPEG2()
const CRC::Parameters< crcpp_uint32, 32 > & CRC::CRC_32_MPEG2 () inline static
Returns a set of parameters for CRC-32 MPEG-2.
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-32 MPEG-2 has the following parameters and check value:
polynomial = 0x04C11DB7
initial value = 0xFFFFFFFF
final XOR = 0x00000000
reflect input = false
reflect output = false
check value = 0x0376E6E7
Returns
CRC-32 MPEG-2 parameters
Definition at line 1982 of file CRC.h.
 {
     static const Parameters<crcpp_uint32, 32> parameters = { 0x04C11DB7, 0xFFFFFFFF, 0x00000000, false, false };
     return parameters;
 }
CRC_32_POSIX()
const CRC::Parameters< crcpp_uint32, 32 > & CRC::CRC_32_POSIX () inline static
Returns a set of parameters for CRC-32 POSIX.
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-32 POSIX has the following parameters and check value:
polynomial = 0x04C11DB7
initial value = 0x00000000
final XOR = 0xFFFFFFFF
reflect input = false
reflect output = false
check value = 0x765E7680
Returns
CRC-32 POSIX parameters
Definition at line 2000 of file CRC.h.
 {
     static const Parameters<crcpp_uint32, 32> parameters = { 0x04C11DB7, 0x00000000, 0xFFFFFFFF, false, false };
     return parameters;
 }
CRC_8()
const CRC::Parameters< crcpp_uint8, 8 > & CRC::CRC_8 () inline static
Returns a set of parameters for CRC-8 SMBus.
Note
The parameters are static and are delayed-constructed to reduce memory footprint.
CRC-8 SMBus has the following parameters and check value:
polynomial = 0x07
initial value = 0x00
final XOR = 0x00
reflect input = false
reflect output = false
check value = 0xF4
Returns
CRC-8 SMBus parameters
Definition at line 1193 of file CRC.h.
 {
     static const Parameters<crcpp_uint8, 8> parameters = { 0x07, 0x00, 0x00, false, false };
     return parameters;
 }
Finalize()
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::Finalize (CRCType remainder, CRCType finalXOR, bool reflectOutput) inline static private
Computes the final reflection and XOR of a CRC remainder.
Parameters
[in] remainder CRC remainder to reflect and XOR
[in] finalXOR Final value to XOR with the remainder
[in] reflectOutput true to reflect each byte of the remainder before the XOR
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
Final CRC
Definition at line 706 of file CRC.h.
 {
     // For masking off the bits for the CRC (in the event that the number of bits in CRCType is larger than CRCWidth)
     static crcpp_constexpr CRCType BIT_MASK = (CRCType(1) << (CRCWidth - CRCType(1))) |
                                              ((CRCType(1) << (CRCWidth - CRCType(1))) - CRCType(1));
     if (reflectOutput)
     {
         remainder = Reflect(remainder, CRCWidth);
     }
     return (remainder ^ finalXOR) & BIT_MASK;
 }
References crcpp_constexpr, and Reflect().
operator=()
CRC& CRC::operator= (const CRC & other) private
Reflect()
template<typename IntegerType > IntegerType CRC::Reflect (IntegerType value, crcpp_uint16 numBits) inline static private
Reflects (i.e. reverses the bits within) an integer value.
Parameters
[in] value Value to reflect
[in] numBits Number of bits in the integer which will be reflected
Template Parameters
IntegerType Integer type of the value being reflected
Returns
Reflected value
Definition at line 683 of file CRC.h.
 {
     IntegerType reversedValue(0);
     for (crcpp_uint16 i = 0; i < numBits; ++i)
     {
         reversedValue = static_cast<IntegerType>((reversedValue << 1) | (value & 1));
         value = static_cast<IntegerType>(value >> 1);
     }
     return reversedValue;
 }
References crcpp_uint16.
Referenced by CalculateRemainder(), CalculateRemainderBits(), Finalize(), and UndoFinalize().
UndoFinalize()
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::UndoFinalize (CRCType crc, CRCType finalXOR, bool reflectOutput) inline static private
Undoes the process of computing the final reflection and XOR of a CRC remainder.
Note
This function allows for computation of multi-part CRCs
Calling UndoFinalize() followed by Finalize() (or vice versa) will always return the original remainder value:
CRCType x = ...;
CRCType y = Finalize(x, finalXOR, reflectOutput);
CRCType z = UndoFinalize(y, finalXOR, reflectOutput);
assert(x == z);
Parameters
[in] crc Reflected and XORed CRC
[in] finalXOR Final value XORed with the remainder
[in] reflectOutput true if the remainder is to be reflected
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
Un-finalized CRC remainder
Definition at line 738 of file CRC.h.
 {
     // For masking off the bits for the CRC (in the event that the number of bits in CRCType is larger than CRCWidth)
     static crcpp_constexpr CRCType BIT_MASK = (CRCType(1) << (CRCWidth - CRCType(1))) |
                                              ((CRCType(1) << (CRCWidth - CRCType(1))) - CRCType(1));
     crc = (crc & BIT_MASK) ^ finalXOR;
     if (reflectOutput)
     {
         crc = Reflect(crc, CRCWidth);
     }
     return crc;
 }
References crcpp_constexpr, and Reflect().
The documentation for this class was generated from the following file:
src/CRC.h