ultra64: ultra64::ROM Class Reference
ultra64::ROM Class Reference
#include <ROM.hpp>
Public Member Functions
ROM ()
std::byte * get_pointer ()
void Open (N64 *n64, std::string filename)
const size_t size ()
Public Attributes
std::byte * data = nullptr
const ROM_header * header
Private Member Functions
void byte_swap ()
Private Attributes
std::string filename
size_t filesize = 0
Detailed Description
Definition at line 27 of file ROM.hpp.
Constructor & Destructor Documentation
ROM()
ROM::ROM ()
Definition at line 18 of file ROM.cpp.
 {
 }
Member Function Documentation
byte_swap()
void ROM::byte_swap () private
Definition at line 82 of file ROM.cpp.
 {
     for(size_t count = 0; count < this->filesize; count += 2)
     {
         uint8_t *ptr = (uint8_t *)(this->data + count);
         uint16_t hword = *(uint16_t *)ptr;
         ptr[0] = (hword & 0xFF00) >> 8;
         ptr[1] = hword & 0x00FF;
     }
 }
References data, and filesize.
Referenced by Open().
get_pointer()
std::byte * ROM::get_pointer ()
Definition at line 99 of file ROM.cpp.
 {
     return this->data;
 }
References data.
Referenced by start().
Open()
void ROM::Open (N64 * n64, std::string filename)
Definition at line 22 of file ROM.cpp.
 {
     this->filename = filename;
     std::fstream file;
     file.open(filename.c_str(), std::fstream::in);
     if(!file.good())
     {
         throw std::runtime_error("Couldn't open file " +  filename);
     }
     std::cout << "Reading " << filename << std::endl;
     file.seekg(0, std::ios::end);
     this->filesize = file.tellg();
     this->data = new std::byte[this->filesize];
     file.seekg(0, std::ios::beg);
     file.read((char *)this->data, this->filesize);
     file.close();
     std::cout << "File format: ";
     this->header = (ROM_header *)this->data;
     switch(header->signature)
     {
         case ROM_HIGHLOW:
             std::cout << "Byte-swapped" << std::endl;
             this->byte_swap();
             break;
         case ROM_LOWHIGH:
             std::cout << "Not byte-swapped" << std::endl;
             break;
         default:
             std::cout << "Unknown format - 0x" << std::hex << header->signature << std::endl;
             break;
     }
     std::cout << "Game name: " << this->header->name << std::endl;
     std::cout << "PC: 0x" << std::hex << this->header->pc << std::endl;
     ultra64::map_memory(n64->mmu, "rom", 0x10000000, this->filesize, 0x0FBFFFFF, new std::byte[this->filesize], nullptr, nullptr);
     uint32_t count = 0;
     uint32_t *v = (uint32_t *)this->data;
     while(count < this->filesize)
     {
         n64->mmu->write_word_raw(0x10000000 + count, *v);
         v++;
         count += 4;
     }
     for(auto &[name, section] : n64->mmu->memory)
     {
         if(name != "rom") continue;
         section.write_handler = &rom_write;
         section.read_handler = &rom_read;
     }
 }
References byte_swap(), data, filename, filesize, header, ultra64::map_memory(), ultra64::MMU::memory, ultra64::N64::mmu, name, ultra64::ROM_header::name, ultra64::ROM_header::pc, ROM_HIGHLOW, ROM_LOWHIGH, rom_read(), rom_write(), ultra64::ROM_header::signature, and ultra64::MMU::write_word_raw().
Referenced by start().
size()
const size_t ROM::size ()
Definition at line 94 of file ROM.cpp.
 {
     return this->filesize;
 }
References filesize.
Member Data Documentation
data
std::byte* ultra64::ROM::data = nullptr
Definition at line 35 of file ROM.hpp.
Referenced by byte_swap(), get_pointer(), and Open().
filename
std::string ultra64::ROM::filename private
Definition at line 37 of file ROM.hpp.
Referenced by Open().
filesize
size_t ultra64::ROM::filesize = 0 private
Definition at line 38 of file ROM.hpp.
Referenced by byte_swap(), Open(), and size().
header
const ROM_header* ultra64::ROM::header
Definition at line 31 of file ROM.hpp.
Referenced by Open(), and start().
The documentation for this class was generated from the following files:
src/n64/ROM.hpp
src/n64/ROM.cpp