ultra64: ultra64::MMU Class Reference
ultra64::MMU Class Reference
#include <MMU.hpp>
Public Member Functions
MMU ()
~MMU ()
void Dump ()
memory_section get_section (uint32_t addr)
uint32_t read_word (uint32_t addr)
uint32_t read_word_impl (uint32_t addr, bool call_handler)
uint32_t read_word_raw (uint32_t addr)
void register_memory (std::string name, memory_section s)
void write_word (uint32_t addr, uint32_t value)
void write_word_impl (uint32_t addr, uint32_t value, bool call_handler)
void write_word_raw (uint32_t addr, uint32_t value)
Public Attributes
std::unordered_map< std::string, memory_section > memory
Detailed Description
Definition at line 23 of file MMU.hpp.
Constructor & Destructor Documentation
MMU()
MMU::MMU ()
Definition at line 125 of file MMU.cpp.
 {
     map_memory(this, "pif_ram", 0x1FC007C0, 0x40, 0x40, new std::byte[0x40], &pif_ram_write, nullptr);
     map_memory(this, "sp_dmem", 0x04000000, 0x1000, 0x1000, new std::byte[0x1000], &sp_dmem_write, nullptr);
     map_memory(this, "sp_imem", 0x04001000, 0x1000, 0x1000, new std::byte[0x1000], nullptr, nullptr);
     map_memory(this, "sp_registers", 0x04040000, 0x20, 0x20, new std::byte[0x20], &sp_register_write, &sp_register_read);
     map_memory(this, "dp_registers", 0x04100000, 0x20, 0x20, new std::byte[0x20], &dp_register_write, &dp_register_read);
     map_memory(this, "vi_registers", 0x04400000, 0x38, 0x38, new std::byte[0x38], nullptr, nullptr);
     map_memory(this, "ai_registers", 0x04500000, 0x18, 0x18, new std::byte[0x18], nullptr, nullptr);
     map_memory(this, "pi_registers", 0x04600000, 0x34, 0x34, new std::byte[0x34], &pi_register_write, nullptr);
     map_memory(this, "si_registers", 0x04800000, 0x1C, 0x1C, new std::byte[0x1C], nullptr, &si_register_read);
     map_memory(this, "dd_ipl_rom", 0x06000000, 0x400000, 0x400000, new std::byte[0x400000], nullptr, nullptr);
 }
References dp_register_read(), dp_register_write(), ultra64::map_memory(), pi_register_write(), pif_ram_write(), si_register_read(), sp_dmem_write(), sp_register_read(), and sp_register_write().
~MMU()
MMU::~MMU ()
Definition at line 148 of file MMU.cpp.
 {
     return;
     for(const auto &it : this->memory)
     {
         if(it.first.size() == 0) continue;
         std::cout << "Deleting " << it.first << std::endl;
         memory_section s = it.second;
         delete s.ptr;
         this->memory.erase(it.first);
     }
 }
References memory, and ultra64::memory_section::ptr.
Member Function Documentation
Dump()
void MMU::Dump ()
Definition at line 139 of file MMU.cpp.
 {
     std::cout << std::dec << this->memory.size() << " memory areas" << std::endl;
     for(const auto &[name, section] : this->memory)
     {
         std::cout << name << ": " << std::dec << section.size << " bytes at " << std::hex << section.offset << std::endl;
     }
 }
References memory, and name.
get_section()
memory_section MMU::get_section (uint32_t addr)
Definition at line 166 of file MMU.cpp.
 {
     for(const auto &it : this->memory)
     {
         memory_section s = it.second;
         if(addr >= s.offset && addr < (s.offset + s.max_size))
         {
             if(addr - s.offset > s.size)
             {
                 std::stringstream ss;
                 ss << it.first << " address " << std::hex << addr << " out of bounds.";
                 throw std::runtime_error(ss.str());
             }
             s.addr = addr;
             return s;
         }
     }
     std::stringstream ss;
     ss << "Unknown memory address: " << std::hex << addr;
     throw std::runtime_error(ss.str());
 }
References ultra64::memory_section::addr, ultra64::memory_section::max_size, memory, ultra64::memory_section::offset, and ultra64::memory_section::size.
Referenced by read_word_impl(), and write_word_impl().
read_word()
uint32_t MMU::read_word (uint32_t addr)
Definition at line 219 of file MMU.cpp.
 {
     return this->read_word_impl(addr, true);
 }
References read_word_impl().
Referenced by ultra64::vr4300::step().
read_word_impl()
uint32_t MMU::read_word_impl (uint32_t addr, bool call_handler)
Definition at line 229 of file MMU.cpp.
 {
     uint32_t phys_addr = addr & 0x1FFFFFFF;
     memory_section s = get_section(phys_addr);
     uint32_t pointer = phys_addr - s.offset;
     uint32_t value = *(uint32_t *)(s.ptr + pointer);
     if(!call_handler) return value;
     if(s.read_handler != nullptr) s.read_handler(this, s, value);
     return value;
 }
References get_section(), ultra64::memory_section::offset, ultra64::memory_section::ptr, and ultra64::memory_section::read_handler.
Referenced by read_word(), and read_word_raw().
read_word_raw()
uint32_t MMU::read_word_raw (uint32_t addr)
Definition at line 224 of file MMU.cpp.
 {
     return this->read_word_impl(addr, false);
 }
References read_word_impl().
Referenced by DebuggerWindow::view().
register_memory()
void MMU::register_memory (std::string name, memory_section s)
Definition at line 161 of file MMU.cpp.
 {
     this->memory[name] = s;
 }
References memory, and name.
Referenced by ultra64::map_memory().
write_word()
void MMU::write_word (uint32_t addr, uint32_t value)
Definition at line 189 of file MMU.cpp.
 {
     this->write_word_impl(addr, value, true);
 }
References write_word_impl().
write_word_impl()
void MMU::write_word_impl (uint32_t addr, uint32_t value, bool call_handler)
Definition at line 199 of file MMU.cpp.
 {
     uint32_t phys_addr = addr & 0x1FFFFFFF;
     memory_section s;
     try {
         s = get_section(phys_addr);
     } catch (std::runtime_error &e) {
         std::stringstream ss;
         ss << "Failed to write " << std::hex << value << ". " << e.what();
         throw std::runtime_error(ss.str());
     }
     uint32_t offset = phys_addr - s.offset;
     uint32_t *p = (uint32_t *)(s.ptr + offset);
     *p = value;
     if(!call_handler) return;
     if(s.write_handler != nullptr) s.write_handler(this, s, value);
 }
References get_section(), ultra64::memory_section::offset, ultra64::memory_section::ptr, and ultra64::memory_section::write_handler.
Referenced by write_word(), and write_word_raw().
write_word_raw()
void MMU::write_word_raw (uint32_t addr, uint32_t value)
Definition at line 194 of file MMU.cpp.
 {
     this->write_word_impl(addr, value, false);
 }
References write_word_impl().
Referenced by ultra64::N64::load_pif_rom(), ultra64::ROM::Open(), and ultra64::RSP::set_n64().
Member Data Documentation
memory
std::unordered_map<std::string, memory_section> ultra64::MMU::memory
Definition at line 37 of file MMU.hpp.
Referenced by ~MMU(), Dump(), get_section(), ultra64::ROM::Open(), and register_memory().
The documentation for this class was generated from the following files:
src/n64/MMU.hpp
src/n64/MMU.cpp