ultra64: MainWindow Class Reference
MainWindow Class Reference
#include <MainWindow.hpp>
Public Member Functions
MainWindow (const wxString &title, const wxPoint &pos, const wxSize &size)
Private Member Functions
void OnDebugPIFROM (wxCommandEvent &event)
void OnDebugRegisters (wxCommandEvent &event)
void OnDebugROM (wxCommandEvent &event)
void OnExit (wxCommandEvent &event)
void OnLoadState (wxCommandEvent &event)
void OnOpenROM (wxCommandEvent &event)
void OnPaint (wxPaintEvent &event)
void OnSaveState (wxCommandEvent &event)
void OnSelectPIFROM (wxCommandEvent &event)
wxDECLARE_EVENT_TABLE ()
Detailed Description
Definition at line 5 of file MainWindow.hpp.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (const wxString & title, const wxPoint & pos, const wxSize & size)
Definition at line 23 of file MainWindow.cpp.
         : wxFrame(NULL, wxID_ANY, title, pos, size)
 {
     wxMenu *menuFile = new wxMenu;
     menuFile->Append(ID_open_rom, "&Open ROM", "");
     menuFile->Append(ID_select_pif_rom, "Select &PIF ROM", "");
     menuFile->Append(wxID_EXIT);
     wxMenu *menuState = new wxMenu;
     menuState->Append(ID_save_state, "&Save state", "");
     menuState->Append(ID_load_state, "&Load state", "");
     wxMenu *menuDebug = new wxMenu;
     menuDebug->Append(ID_debug_pif_rom, "View &PIF ROM", "");
     menuDebug->Append(ID_debug_rom, "View &ROM", "");
     menuDebug->Append(ID_debug_registers, "View R&egisters", "");
     wxMenuBar *menuBar = new wxMenuBar;
     menuBar->Append(menuFile, "&File");
     menuBar->Append(menuState, "&State");
     menuBar->Append(menuDebug, "&Debug");
     SetMenuBar(menuBar);
     CreateStatusBar(1);
 }
References ID_debug_pif_rom, ID_debug_registers, ID_debug_rom, ID_load_state, ID_open_rom, ID_save_state, and ID_select_pif_rom.
Member Function Documentation
OnDebugPIFROM()
void MainWindow::OnDebugPIFROM (wxCommandEvent & event) private
Definition at line 106 of file MainWindow.cpp.
 {
     open_debugger();
     wxGetApp().debugger->view(0x1FC00000, 0x1FC007BF);
 }
References open_debugger().
OnDebugRegisters()
void MainWindow::OnDebugRegisters (wxCommandEvent & event) private
Definition at line 118 of file MainWindow.cpp.
 {
     if(!wxGetApp().registers)
     {
         wxGetApp().registers = new RegistersWindow(wxGetApp().frame,
                                "Registers", wxPoint(200, 50), wxSize(820, 450));
     }
     wxGetApp().registers->SetBackgroundColour(wxColour(*wxWHITE));
     wxGetApp().registers->Show(true);
     wxGetApp().registers->UpdateRegisters(render_registers(wxGetApp().n64));
 }
References render_registers().
OnDebugROM()
void MainWindow::OnDebugROM (wxCommandEvent & event) private
Definition at line 112 of file MainWindow.cpp.
 {
     open_debugger();
     wxGetApp().debugger->view(0x10000000, 0x10008000);
 }
References open_debugger().
OnExit()
void MainWindow::OnExit (wxCommandEvent & event) private
Definition at line 54 of file MainWindow.cpp.
 {
     Close(true);
 }
OnLoadState()
void MainWindow::OnLoadState (wxCommandEvent & event) private
Definition at line 137 of file MainWindow.cpp.
 {
     Json::Value state;
     std::ifstream state_file("./mario64.save");
     state_file >> state;
     wxGetApp().n64->cpu.load_state(state);
 }
OnOpenROM()
void MainWindow::OnOpenROM (wxCommandEvent & event) private
Definition at line 75 of file MainWindow.cpp.
 {
     std::string rom_path = wxGetApp().config["rom_path"].asString();
     wxFileDialog rom_dialog(this, _("Open N64 ROM file"), rom_path, "",
                                 "N64 ROM files (*.n64;*.v64;*.z64;*.bin)|*.n64;*.v64;*.bin|All files (*.*)|*.*",
                                 wxFD_OPEN|wxFD_FILE_MUST_EXIST);
     if(wxID_CANCEL == rom_dialog.ShowModal()) return;
     std::string directory = rom_dialog.GetDirectory().ToStdString();
     wxGetApp().config["rom_path"] = directory;
     wxGetApp().save_config();
     std::string rom = rom_dialog.GetPath().ToStdString();
     std::cout << "Opening " << rom << std::endl;
     start(rom);
 }
References start().
OnPaint()
void MainWindow::OnPaint (wxPaintEvent & event) private
Definition at line 49 of file MainWindow.cpp.
 {
     wxPaintDC dc(this);
 }
OnSaveState()
void MainWindow::OnSaveState (wxCommandEvent & event) private
Definition at line 131 of file MainWindow.cpp.
 {
     Json::Value state = wxGetApp().n64->cpu.save_state();
     std::cout << state << std::endl;
 }
OnSelectPIFROM()
void MainWindow::OnSelectPIFROM (wxCommandEvent & event) private
Definition at line 59 of file MainWindow.cpp.
 {
     std::string pif_path = wxGetApp().config["pif_rom_path"].asString();
     wxFileDialog rom_dialog(this, _("Open PIF ROM file"), pif_path, "",
                                 "ROM files (*.bin)|*.bin|All files (*.*)|*.*",
                                 wxFD_OPEN|wxFD_FILE_MUST_EXIST);
     if(wxID_CANCEL == rom_dialog.ShowModal()) return;
     std::string filename = rom_dialog.GetFilename().ToStdString();
     if(!filename.size()) return;
     wxGetApp().config["pif_rom"] = filename;
     wxGetApp().save_config();
 }
wxDECLARE_EVENT_TABLE()
MainWindow::wxDECLARE_EVENT_TABLE () private
The documentation for this class was generated from the following files:
src/MainWindow.hpp
src/MainWindow.cpp