ultra64: CRC::Table< CRCType, CRCWidth > Struct Template Reference
CRC::Table< CRCType, CRCWidth > Struct Template Reference
CRC lookup table. After construction, the CRC parameters are fixed.
#include <CRC.h>
Public Member Functions
Table (const Parameters< CRCType, CRCWidth > &parameters)
Constructs a CRC table from a set of CRC parameters.
const Parameters< CRCType, CRCWidth > & GetParameters () const
Gets the CRC parameters used to construct the CRC table.
const CRCType * GetTable () const
Gets the CRC table.
CRCType operator[] (unsigned char index) const
Gets an entry in the CRC table.
Private Member Functions
void InitTable ()
Initializes a CRC table.
Private Attributes
Parameters< CRCType, CRCWidth > parameters
CRC parameters used to construct the table.
CRCType table [1<< CHAR_BIT]
CRC lookup table.
Detailed Description
template<typename CRCType, crcpp_uint16 CRCWidth>
struct CRC::Table< CRCType, CRCWidth >
CRC lookup table. After construction, the CRC parameters are fixed.
Note
A CRC table can be used for multiple CRC calculations.
Definition at line 169 of file CRC.h.
Constructor & Destructor Documentation
Table()
template<typename CRCType , crcpp_uint16 CRCWidth> CRC::Table< CRCType, CRCWidth >::Table (const Parameters< CRCType, CRCWidth > & params) inline
Constructs a CRC table from a set of CRC parameters.
Parameters
[in] params CRC parameters
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Definition at line 347 of file CRC.h.
                                                                                       :
     parameters(params)
 {
     InitTable();
 }
References CRC::Table< CRCType, CRCWidth >::InitTable().
Member Function Documentation
GetParameters()
template<typename CRCType , crcpp_uint16 CRCWidth> const CRC::Parameters< CRCType, CRCWidth > & CRC::Table< CRCType, CRCWidth >::GetParameters () const inline
Gets the CRC parameters used to construct the CRC table.
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC parameters
Definition at line 375 of file CRC.h.
 {
     return parameters;
 }
Referenced by CRC::Calculate(), CRC::CalculateBits(), and CRC::CalculateRemainder().
GetTable()
template<typename CRCType , crcpp_uint16 CRCWidth> const CRCType * CRC::Table< CRCType, CRCWidth >::GetTable () const inline
Gets the CRC table.
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC table
Definition at line 387 of file CRC.h.
 {
     return table;
 }
InitTable()
template<typename CRCType , crcpp_uint16 CRCWidth> void CRC::Table< CRCType, CRCWidth >::InitTable () inline private
Initializes a CRC table.
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Definition at line 411 of file CRC.h.
 {
     // For masking off the bits for the CRC (in the event that the number of bits in CRCType is larger than CRCWidth)
     static crcpp_constexpr CRCType BIT_MASK((CRCType(1) << (CRCWidth - CRCType(1))) |
                                            ((CRCType(1) << (CRCWidth - CRCType(1))) - CRCType(1)));
     // The conditional expression is used to avoid a -Wshift-count-overflow warning.
     static crcpp_constexpr CRCType SHIFT((CHAR_BIT >= CRCWidth) ? static_cast<CRCType>(CHAR_BIT - CRCWidth) : 0);
     CRCType crc;
     unsigned char byte = 0;
     // Loop over each dividend (each possible number storable in an unsigned char)
     do
     {
         crc = CRC::CalculateRemainder<CRCType, CRCWidth>(&byte, sizeof(byte), parameters, CRCType(0));
         // This mask might not be necessary; all unit tests pass with this line commented out,
         // but that might just be a coincidence based on the CRC parameters used for testing.
         // In any case, this is harmless to leave in and only adds a single machine instruction per loop iteration.
         crc &= BIT_MASK;
         if (!parameters.reflectInput && CRCWidth < CHAR_BIT)
         {
             // Undo the special operation at the end of the CalculateRemainder()
             // function for non-reflected CRCs < CHAR_BIT.
             crc = static_cast<CRCType>(crc << SHIFT);
         }
         table[byte] = crc;
     }
     while (++byte);
 }
References crcpp_constexpr.
Referenced by CRC::Table< CRCType, CRCWidth >::Table().
operator[]()
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::Table< CRCType, CRCWidth >::operator[] (unsigned char index) const inline
Gets an entry in the CRC table.
Parameters
[in] index Index into the CRC table
Template Parameters
CRCType Integer type for storing the CRC result
CRCWidth Number of bits in the CRC
Returns
CRC table entry
Definition at line 400 of file CRC.h.
 {
     return table[index];
 }
Member Data Documentation
parameters
template<typename CRCType , crcpp_uint16 CRCWidth> Parameters<CRCType, CRCWidth> CRC::Table< CRCType, CRCWidth >::parameters private
CRC parameters used to construct the table.
Definition at line 187 of file CRC.h.
table
template<typename CRCType , crcpp_uint16 CRCWidth> CRCType CRC::Table< CRCType, CRCWidth >::table[1<< CHAR_BIT] private
CRC lookup table.
Definition at line 188 of file CRC.h.
The documentation for this struct was generated from the following file:
src/CRC.h