ultra64: src/ultra64.hpp File Reference
ultra64.hpp File Reference
#include <wx/wx.h>
#include <json/json.h>
#include "n64/N64.hpp"
#include "MainWindow.hpp"
#include "RegistersWindow.hpp"
#include "DebuggerWindow.hpp"
Classes
class wxUltra64
Enumerations
enum {
ID_select_pif_rom = 1 , ID_open_rom = 2 , ID_save_state = 3 , ID_load_state = 4 ,
ID_debug_pif_rom = 10 , ID_debug_rom = 11 , ID_debug_registers = 12 , BUTTON_cpu_step = 20
}
Functions
std::vector< std::string > render_registers (ultra64::N64 *n64)
void start (std::string filename)
Variables
const int ID_CPU_STEP_COUNT = 102
const int ID_DEBUGGER_PC = 103
const int ID_MEMORY_LISTBOX = 100
const int ID_REGISTERS_LISTBOX = 101
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ID_select_pif_rom
ID_open_rom
ID_save_state
ID_load_state
ID_debug_pif_rom
ID_debug_rom
ID_debug_registers
BUTTON_cpu_step
Definition at line 29 of file ultra64.hpp.
 {
     ID_select_pif_rom = 1,
     ID_open_rom = 2,
     ID_save_state = 3,
     ID_load_state = 4,
     ID_debug_pif_rom = 10,
     ID_debug_rom = 11,
     ID_debug_registers = 12,
     BUTTON_cpu_step = 20,
 };
Function Documentation
render_registers()
std::vector<std::string> render_registers (ultra64::N64 * n64)
Definition at line 108 of file ultra64.cpp.
 {
     std::vector<std::string> data;
     char temp[1024];
     uint32_t count = 0;
     while(count < 32)
     {
         sprintf(temp, "GPR[%.2d]=0x%.16lX  GPR[%.2d]=0x%.16lX  CP0[%.2d]=0x%.16lX  CP0[%.2d]=0x%.16lX",
                 count, n64->cpu.GPR[count], count + 1, n64->cpu.GPR[count + 1],
                 count, n64->cpu.CP0[count], count + 1, n64->cpu.CP0[count + 1]);
         data.push_back(temp);
         count += 2;
     }
     sprintf(temp, "HI=0x%.4x  LO=0x%.4x", n64->cpu.HI, n64->cpu.LO);
     data.push_back(temp);
     sprintf(temp, "PC = 0x%.8X", n64->cpu.PC);
     data.push_back(temp);
     return data;
 }
References ultra64::vr4300::CP0, ultra64::N64::cpu, ultra64::vr4300::GPR, ultra64::vr4300::HI, ultra64::vr4300::LO, and ultra64::vr4300::PC.
Referenced by DebuggerWindow::OnCPUStep(), MainWindow::OnDebugRegisters(), and start().
start()
void start (std::string filename)
Definition at line 132 of file ultra64.cpp.
 {
     if(wxGetApp().n64 != nullptr) delete wxGetApp().n64;
     wxGetApp().n64 = new ultra64::N64();
     ultra64::N64 *n64 = wxGetApp().n64;
     try
     {
         load_pif_rom(n64);
     }
     catch (std::runtime_error &e)
     {
         wxGetApp().frame->SetStatusText(e.what(), 0);
     }
     if(filename.size() == 0) return;
     n64->rom = new ultra64::ROM();
     n64->rom->Open(n64, filename);
     uint32_t crc = CRC::Calculate((n64->rom->get_pointer() + 0x40), 0xFC0, CRC::CRC_32());
     std::cout << "CRC = " << std::hex << crc << std::endl;
     switch(crc)
     {
         case crc_nus_6102:
             std::cout << "CIC seed: " << std::hex << cic_seed_nus_6102 << std::endl;
             try {
                 wxGetApp().n64->mmu->write_word(0x1FC007C0 + 0x24, cic_seed_nus_6102);
             } catch(std::runtime_error &e) {
                 std::cerr << e.what() << std::endl;
                 return;
             }
             break;
         default:
             std::cerr << "No matching CIC seed for CRC: " << std::hex << crc << std::endl;
             break;
     }
     std::stringstream ss;
     ss << "Ultra 64 - " << n64->rom->header->name;
     wxGetApp().frame->SetTitle(ss.str());
     wxGetApp().n64->mmu->write_word_raw(SP_DMA_BUSY_REG, 0x0);
 return;
     while(1)
     {
         try {
             wxGetApp().n64->cpu.step();
         } catch(std::runtime_error &e) {
             std::cerr << e.what() << std::endl;
             return;
         }
         if(wxGetApp().registers) wxGetApp().registers->UpdateRegisters(render_registers(wxGetApp().n64));
     }
 }
References CRC::Calculate(), cic_seed_nus_6102, CRC::CRC_32(), crc_nus_6102, ultra64::ROM::get_pointer(), ultra64::ROM::header, load_pif_rom(), ultra64::ROM_header::name, ultra64::ROM::Open(), render_registers(), ultra64::N64::rom, and SP_DMA_BUSY_REG.
Referenced by wxUltra64::OnInit(), and MainWindow::OnOpenROM().
Variable Documentation
ID_CPU_STEP_COUNT
const int ID_CPU_STEP_COUNT = 102
Definition at line 12 of file ultra64.hpp.
Referenced by wxBEGIN_EVENT_TABLE().
ID_DEBUGGER_PC
const int ID_DEBUGGER_PC = 103
Definition at line 13 of file ultra64.hpp.
Referenced by wxBEGIN_EVENT_TABLE().
ID_MEMORY_LISTBOX
const int ID_MEMORY_LISTBOX = 100
Definition at line 10 of file ultra64.hpp.
Referenced by wxBEGIN_EVENT_TABLE().
ID_REGISTERS_LISTBOX
const int ID_REGISTERS_LISTBOX = 101
Definition at line 11 of file ultra64.hpp.
Referenced by RegistersWindow::RegistersWindow().